- Makefile
- Pipfile
- Pipfile.lock
Add [`pytest-cov`](https://pytest-cov.readthedocs.io/en/latest/) as a dev dependency so it's easy to generate Code Coverage reports for test runs.
> Add PyTest coverage reporting

- basilisp/compiler.py
- basilisp/lang/runtime.py
- basilisp/util.py
- tests/maybe_test.py
Add a Maybe optional to make code handling `None` less painful. This Maybe object is modeled after the Java [`Optional`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html) type added in Java 8.
> Add Maybe optional to make it easier to handle None

- basilisp/compiler.py
- basilisp/importer.py
In a previous PR, work was done to fully compile Basilisp namespaces in a single
file down into a corresponding Python module which would be usable as a standard
Python module. This caused trouble applying macros during the compilation phase,
because it meant that the entire namespace was compiled and executed at once,
rather than piecemeal. Without the runtime updating with each addition of a
function or definition to a namespace, macros did not exist and no code was
generated.
This PR adds a hack on top of the compiler to run incremental compilation of
Basilisp code in parallel with the standard module generation process to allow
the runtime to be built up as the module is being compiled (and therefore allow
macros to exist).
> Fix an issue where macros were not applied compiling full modules

- basilisp/compiler.py
> Use generated symbols for import aliases to reduce likelihood of a def name clash

- basilisp/compiler.py
- tests/compiler_test.py
> Don't throw exception for list without symbol first in macroexpansion

- basilisp/compiler.py
- basilisp/lang/typing.py
- basilisp/lang/util.py
- basilisp/reader.py
- tests/compiler_test.py
- tests/reader_test.py
> Add support for complex, Decimal, and Fraction suffixes

- src/basilisp/importer.py
- src/basilisp/lang/util.py
- tests/basilisp/importer_test.py
- tests/basilisp/langutil_test.py
- tests/basilisp/testrunner_test.py
Basilisp namespaces permit a wide range of punctuation marks which are not permitted in Python module or variable names. Basilisp hooks Python's import machinery to do much of the import work, so whenever a standard Python import is called with a munged Basilisp name, we used to generate the Namespace _with that munged name_. This led to orphaned Namespaces in the global Namespace cache and possibly inconsistent state.
This PR coerces imported Namespace names back to their Basilisp originals and generates the Namespace from that demunged name.
Fixes #206
> Demunge namespaces specified via Python import machinery

- src/basilisp/core/__init__.lpy
- src/basilisp/test.lpy
> Capture the current namespace in deftest

- tox.ini
Add `mypy` and `safety` targets back to Tox's config for TravisCI.
> Add MyPy and Safety targets back to Tox for TravisCI

- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
> Allow more flexible interop property access syntax for macros

- src/basilisp/core/__init__.lpy
Later sections of `basilisp.core` were organized into logical groups, so this PR groups some of the original functions which were a hodgepodge before.
> Reorganize basilisp.core into more logical groups

- .gitattributes
- Pipfile.lock
Silence the security update from GitHub by updating our `requests` dependency version in `Pipfile.lock`.
> Update Pipfile.lock dependencies

- src/basilisp/cli.py
- src/basilisp/lang/compiler.py
- tests/basilisp/compiler_test.py
- tox.ini
> Emit compiler warning when Var and local names are shadowed

- src/basilisp/core/__init__.lpy
- src/basilisp/lang/compiler.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
> Allow Python imports to be aliased like a Basilisp require

- src/basilisp/lang/map.py
- src/basilisp/lang/obj.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/vector.py
- src/basilisp/testrunner.py
- tests/basilisp/vector_test.py
Remove some superfluous `functional.seq` calls which were equivalent to the builtin `map` function.
> Remove superfluous functional.seq calls

- src/basilisp/lang/obj.py
Using a mutable `dict` rather than a `PMap` seems to speed up the test suite (and, likely, non-test code) by _a lot_. No surprise there.
> Use a mutable dict for lrepr kwargs

- Makefile
- src/basilisp/util.py
- src/basilisp/walker.py
- tests/basilisp/lrepr_test.py
- tox.ini
Certain lines that aren't (or can't) covered in standard tests can cause deflated Coverage metrics, so this PR excludes those lines.
> Improve Coverage by ignoring certain unimportant lines

- src/basilisp/lang/reader.py
Functions, deref, and quote forms emitted by the reader did not include `:line` and `:col` meta. This PR adds those meta keys back.
> Attach meta to functions, quote, and deref forms

- src/basilisp/importer.py
- src/basilisp/lang/compiler/__init__.py
- tox.ini
Emitting the generated Python AST to strings and then to stdout or `*generated-python*` Var adds a bit of time to startup, which is a fine price to pay during development, but would be more onerous to normal users. This PR creates an environment var `BASILISP_EMIT_GENERATED_PYTHON` which can be set to disable the emission of generated Python. Eventually, the default value will switch to `false` (when development settles down), but for now having `true` set as the default value is tremendously useful.
> Allow users to disable emitting Python AST strings

- pyproject.toml
- src/basilisp/core/__init__.lpy
- src/basilisp/lang/delay.py
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/list.py
- src/basilisp/lang/map.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/set.py
- src/basilisp/lang/vector.py
After #370, there was a little bit of follow up work to clean up the interface hierarchy to more closely match Clojure.
> Clean up the interface hierarchy

- src/basilisp/lang/compiler/constants.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/parser.py
- tests/basilisp/compiler_test.py
Fixes #381 
Broken out of #374
> Allow default values for deftype* fields

- src/basilisp/core.lpy
- src/basilisp/lang/interfaces.py
- src/basilisp/repl.lpy
- tests/basilisp/core_test.py
Add `ex-cause`, `ex-data`, and `ex-message` for fetching data from exceptions. Move `*1`, `*2`, `*3`, `*e` from `basilisp.repl` to match their definitions in Clojure.
> Add exception details functions

- Pipfile.lock
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/runtime.py
- src/basilisp/repl.lpy
- src/basilisp/string.lpy
- src/basilisp/test.lpy
- tests/basilisp/cli_test.py
- tests/basilisp/compiler_test.py
- tests/basilisp/defrecord_test.lpy
- tests/basilisp/testrunner_test.py
In Basilisp code, we use the namespace `builtins` (which is actually the Python module `builtins`) to refer unambiguously to builtin Python functions and classes. However, this is not very clear to end users what is being called. This PR changes that value to be `python` so it is clearer that callers are using the native Python builtins.
Fixes #398
> Change `builtins` name to `python` in Basilisp code

- .circleci/config.yml
- tox.ini
Start running CircleCI builds with Python 3.8 and allow it to fail until I have time to address changes.
> Start running CircleCI builds with Python 3.8 dev builds

- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/util.py
- tox.ini
* Cache `ctx.current_ns` in the Analyzer and Generator whenever possible
* Do not collect comprehensions into intermediate lists when they will just be put into some other iterable later
* Use `str.translate` for munging, rather than manual translation
Nothing here moves the needle dramatically, but every little bit that shaves a few milliseconds off of the startup time helps.
> A few tiny changes to slightly improve performance

- .gitignore
- .prospector.yaml
- Makefile
- src/basilisp/importer.py
- src/basilisp/lang/util.py
Easy `make` target to dump generated Python for `basilisp.core`.
Also, munge `..` macro name using a kind-of-dirty change to `basilisp.lang.util.munge` 🤷‍♂
> Dump generated `basilisp.core` Python

- CHANGELOG.md
- docs/reader.rst
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
> Throw a Syntax Error when a splicing reader conditional is outside a valid splice context

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
- tests/basilisp/core_macros_test.lpy
> Add `declare`, `defn-`, and `defonce` macros

- CHANGELOG.md
- src/basilisp/cli.py
- src/basilisp/importer.py
- src/basilisp/lang/compiler/__init__.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/typing.py
Switch the Basilisp module type to a custom type, which supports the `__basilisp_bootstrapped__` dunder property by default.
> Typed Basilisp module

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- tests/basilisp/compiler_test.py
> `quote` special form accepts exactly 1 argument

- Pipfile.lock
- src/basilisp/testrunner.py
- tox.ini
* Resolve the [junit_family](https://docs.pytest.org/en/latest/deprecations.html#junit-family-default-value-change-to-xunit2) deprecation in PyTest by fixing the `junit_family` to `xunit2` now.
* Partially address the [Node.from_parent](https://docs.pytest.org/en/latest/deprecations.html#node-construction-changed-to-node-from-parent) deprecation in PyTest 5.4. The construction of `BasilispTestItem` using `from_parent` with custom attributes isn't well described in the PyTest documentation yet, so I'm not going to fix it in this PR. Converting to `BasilispFile.from_parent` was more straightforward with the way the Basilisp plugin is set up.
> Partially support Node.from_parent deprecation in PyTest 5.4

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/compiler/optimizer.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
- tests/basilisp/core_macros_test.lpy
- tests/basilisp/var_test.py
> `defonce` no longer throws a SyntaxError

- CHANGELOG.md
- src/basilisp/lang/interfaces.py
- tests/basilisp/seq_test.py
> Fixed a bug where Basilisp would throw an exception when comparing seqs to non-seqable values

- CHANGELOG.md
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
> Fixed a bug where aliased Python submodule imports referred to the top-level module rather than the submodule

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
> Allow `deftype*` forms to declare no fields

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
This PR is a set of otherwise-independent changes I pulled out of #547. It includes the following changes:
* The titular Function/Method context stored in the `NodeEnv` object of Lisp AST nodes
* Changing the generated module-wide `__NS` variable to `_NS` because I learned that variables prefixed by double underscores are [always mangled](https://bugs.python.org/issue27793) in a class lexical context in Python regardless of the presence of a `global` statement.
* Added a few tests for asserting the resolution of `def`'ed Basilisp Vars match the expected behavior from Clojure
Fixes #548
> Include the Function or Method context in the AST Node environment

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
This PR introduces the concept of a "context boundary" Symbol Table into the analyzer. Such Symbol Tables are defined at the top level of execution contexts such as modules (namespaces), functions (sync and async), and methods. Because imports are globally available once they have been called, we hoist imported symbols to the nearest context boundary Symbol Table, which is considerably different from the standard `let` style case, where a name becomes unavailable after it goes out of scope.
Fixes #544
> More flexible resolution of import and require symbols 

- Pipfile.lock
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/constants.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
Add the `reify*` special form and the `basilisp.core/reify` macro for constructing reified objects. `reify*` allows callers to create objects of anonymous class types satisfying 0 or more Python interfaces (and Basilisp protocols when #460 merges). This was able to use most of the same code as the original `deftype*` implementation, which was convenient. It's worth noting that `reify*` does not currently support classmethods (since the constructor is auto-generated and only accepts one argument - `meta` - anyway) or staticmethods (since the generated type is not directly exposed to users). Methods and Python properties are supported, however.
Partially addresses #425
> Support for reify* form

- src/basilisp/lang/keyword.py
- src/basilisp/lang/map.py
- src/basilisp/lang/obj.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/runtime.py
- tests/basilisp/keyword_test.py
* Correctly use `functools.singledispatch`. Rather than checking `isinstance()` manually and then dispatching to a secondary function via `singledispatch` (_and_ having a backup function with thousands of pointless `isinstance()` branches), I've corrected all of the relevant uses to use `singledispatch` correctly since it's capable of using the object MRO to find the most appropriate implementation.
* Update the Keyword intern cache to just use a simple `threading.Lock` instance rather than using an Atom, since the performance is much better.
> Couple of small performance improvements

- CHANGELOG.md
- Pipfile
- Pipfile.lock
- setup.py
- src/basilisp/core.lpy
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/map.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/set.py
- tests/basilisp/map_test.py
- tests/basilisp/set_test.py
Convert `basilisp.lang.map.Map` and `basilisp.lang.set.Set` to use `immutables.Map` under the hood, rather than the Python-only implementation provided by `pyrsistent`, which should offer some decent performance improvements for both types.
As another performance improvement, most of the basic runtime functions like `first`, `rest`, `cons`, et al were converted to single dispatch (using `@functools.singledispatch`), which should be a little faster than a series of `isinstance` checks.
Fixes #557
> Convert Map to use `immutables.Map` rather than `pyrsistent`

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/constants.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
- tests/basilisp/test_core_fns.lpy
- tests/basilisp/test_core_macros.lpy
- tests/basilisp/test_defrecord.lpy
Add support for "artificially abstract" base classes. The Python ecosystem is much less strict with its use of `abc.ABC` to interfaces than Java (which has a native `interface` construct), so even in where a type may be _in practice_ an interface or ABC, the compiler would not permit you to declare such types as supertypes because they do not inherit from `abc.ABC`. In these cases, users can mark the type as  abstract with the `:abstract` metadata key to force the compiler to accept that it is abstract.
In this case, the compiler will attempt to verify that any extra methods present on the `deftype`, `defrecord`, or `reify` are present on any one of the artificially abstract base classes. This will allow users to override existing class members, but not introduce new ones without a true …
> Support artificially abstract base classes

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/runtime.py
- tests/basilisp/core_test.py
- tests/basilisp/runtime_test.py
- tests/basilisp/test_core_fns.lpy
While working on #568, I discovered a few issues with type support of `nth` and `get`, so I split them out into a separate PR.
* `nth` previously would respond to nearly any collection type, which was incorrect. `nth` should only respond to sequential types, not maps and sets which _can produce_ sequences but are not themselves sequential.
* `get` should technically respond to all types, though in most cases it returns `nil` (or its default value). It should respond to set types as if by calling them with the key. It should respond to all Python types as by `__getitem__`.
Fixes #569
> Fix `nth` and `get` type support

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- tests/basilisp/compiler_test.py
> Allow recursive `def` references inside `def` init values

- CHANGELOG.md
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/keyword.py
- src/basilisp/lang/symbol.py
This PR includes a change to pre-compute the hash of a Keyword a new instance is created. Keyword hashes are used as the lookup key for Keywords inside the intern cache. Keywords are also commonly used as map keys and in other collections requiring hashability, so having a pre-computed hash should help improve performance by not requiring repeated computations of the otherwise static hash.
The compiler now also uses the pre-computed Keyword hash to lookup Keywords directly from the intern cache, which should reduce the cost of repeated lookups (particularly if a function makes heavy use of keywords).
This change appears to have improved the lookup speed by around 9%.
Before these changes:
```
basilisp.user=> (import timeit)
<module 'timeit' from …
```
> Improve the lookup speed for Keywords by pre-computing hash

- .circleci/config.yml
- src/basilisp/_pyast.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/futures.py
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/vector.py
- tox.ini
Circle builds were taking 20-40 minutes running PyPy on one node, which really discouraged me from breaking up PRs into smaller pieces since I'd have to wait often times nearly an hour just to merge in a smaller change.
This PR breaks up Circle builds into multiple different nodes. PyPy runs on three different workers using Circle's builtin `parallelism` and test-splitting features. Each of the CPython test suites run in their own node with MyPy/PyLint (to ensure we're not missing any type or linting errors across versions) and Safety (to ensure dependency versions installed on different versions do not have any known CVEs) checks. CI checks which do not vary by version are checked on Python 3.8, since it's faster than other versions.
> Optimizing CircleCI config to reduce build times

- .circleci/config.yml
- tox.ini
Three fixes for CircleCI:
* No longer lock the version of `six` for tests, since `tox` requires a much higher version of `six` now.
* Include `*.lpy` test files.
* Revert to the `legacy` JUnit family output from PyTest since that seems to be what CircleCI understands for test timings.
> Fix some small issues in CircleCI configs

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/reader.py
- src/basilisp/template.lpy
- src/basilisp/test.lpy
- tests/basilisp/reader_test.py
- tests/basilisp/test_core_macros.lpy
- tests/basilisp/test_edn.lpy
- tests/basilisp/test_walk.lpy
Fixes #597 
Fixes #598 
Two other smaller issues that didn't warrant writing up as issues:
* Rename `tests.basilisp.test-edn` and ` tests.basilisp.test-walk` namespaces so they would be correctly picked up for timing info by CircleCI (and just generally to match the patterns used by the other Basilisp tests).
* Rename `basilisp.core.template` to `basilisp.template` to match Clojure's organization.
> Fix several small bugs

- CHANGELOG.md
- src/basilisp/edn.lpy
- tests/basilisp/test_edn.lpy
* Add a safe `basilisp.edn/write-string` function for emitting only the EDN subset of Clojure data structures (which should be safer than using `pr-str` to print EDN).
* Detach `basilisp.edn`'s default reader tags from those defined in `basilisp.lang.reader`, since we wouldn't want to accidentally add new default reader tags and have `basilisp.edn` support those tags unwittingly.
* Add support for reading `##Inf`, `##-Inf`, and `##NaN` reader constants.
Fixes #560
> Add support for serializing EDN strings

- CHANGELOG.md
- Makefile
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/keyword.py
- src/basilisp/lang/list.py
- src/basilisp/lang/map.py
- src/basilisp/lang/multifn.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/set.py
- src/basilisp/lang/typing.py
- src/basilisp/lang/vector.py
- src/basilisp/testrunner.py
- tests/basilisp/atom_test.py
- tests/basilisp/compiler_test.py
- tests/basilisp/core_test.py
- tests/basilisp/keyword_test.py
- tests/basilisp/list_test.py
- tests/basilisp/map_test.py
- tests/basilisp/multifn_test.py
- tests/basilisp/reader_test.py
- tests/basilisp/runtime_test.py
- tests/basilisp/seq_test.py
- tests/basilisp/set_test.py
- tests/basilisp/vector_test.py
Some small changes:
* Refactor the Analyzer and Generator to use `functools.singledispatch` for some type based dispatch rather than a tree of `if isinstance(...)` branches.
* Rename `List`, `Map`, `Set`, and `Vector` to `PersistentList`, `PersistentMap`, `PersistentSet`, and `PersistentVector` respectively.
> Refactor compiler with singledispatch

- CHANGELOG.md
- pyproject.toml
- src/basilisp/lang/atom.py
- src/basilisp/lang/reference.py
- src/basilisp/lang/runtime.py
- tests/basilisp/atom_test.py
- tox.ini
> Remove Atomos as a dependency in favor of readerwriterlock

- CHANGELOG.md
- src/basilisp/test.lpy
- src/basilisp/testrunner.py
> Update basilisp.test/are macro docstring to reflect the loss of line numbers

- CHANGELOG.md
- src/basilisp/core.lpy
> Fix the `with` macro to match the Python language spec

- .circleci/config.yml
- CHANGELOG.md
- pyproject.toml
- src/basilisp/_pyast.py
- src/basilisp/cli.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/runtime.py
- src/basilisp/prompt.py
- tests/basilisp/runtime_test.py
- tox.ini
Add formal support for Python 3.10 and fix a few other issues:
* Minor typing issues from updating MyPy
* Minor formatting issues from updating Black. Support for Black is limited to versions 20.8b1 and older for Python 3.6.0 and 3.6.1 due to those versions not including the `NoReturn` annotation. Basilisp does not use that annotation though, so it should be fine to allow earlier versions of Python for now. We may eventually drop Python 3.6 support anyway, but there's no strong reason to do so right now.
* Update CircleCI Docker images to use the new `cimg` based images provided by Circle. This simplified some of our build steps, which is nice.
> Add support for Python 3.10

- CHANGELOG.md
- src/basilisp/lang/compiler/__init__.py
Fixes #675 
In order to fetch the expression from an expression, the Basilisp REPL generates a simple function in the current REPL module which returns the expression. Afterwards, the function definition hangs around indefinitely even though the function will never be used or called again. This PR adds code to simply `del` that function from the module so it doesn't hang around eating up memory.
> Delete generated utility functions from REPL namespace after execution

- CHANGELOG.md
- src/basilisp/lang/runtime.py
- tests/basilisp/runtime_test.py
> py->lisp recursively creates lisp objects in maps now

- .prospector.yaml
- CHANGELOG.md
- src/basilisp/contrib/pytest/testrunner.py
- src/basilisp/contrib/sphinx/domain.py
- src/basilisp/importer.py
- src/basilisp/lang/compiler/__init__.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/delay.py
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/keyword.py
- src/basilisp/lang/list.py
- src/basilisp/lang/map.py
- src/basilisp/lang/multifn.py
- src/basilisp/lang/obj.py
- src/basilisp/lang/promise.py
- src/basilisp/lang/queue.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/reference.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/seq.py
- src/basilisp/lang/set.py
- src/basilisp/lang/symbol.py
- src/basilisp/lang/vector.py
- src/basilisp/util.py
- tox.ini
Update to the latest Prospector version (1.10.2 as of this PR) and then remove the unnecessary suppressions and fix the new errors it found.
> Update Prospector version and fix the myriad new errors that appear

- .github/workflows/run-tests.yml
Per [this thread](https://github.com/orgs/community/discussions/36561) it seems that I needed to change the trigger for the workflow to `pull_request` rather than `push` to get builds in the base repo.
> Trigger test runs only on PRs rather than push

- .github/workflows/run-tests.yml
- src/basilisp/io.lpy
- tests/basilisp/compiler_test.py
- tests/basilisp/importer_test.py
- tests/basilisp/test_core_macros.lpy
- tests/basilisp/test_io.lpy
- tests/basilisp/testrunner_test.py
Hi,
could you please review changes to fix the test suite to pass on MS-Windows. It fixes #687.
It also enables the test suite which includes MS-Windows support to pass in #686.
In addition to the document changes, the patch also
- Releases file/dir before removing (monkeypatch.chdir, os/close). MS-Windows will complain about trying to remove a file that is still being used otherwise.
- Add empty server to file: uri (i.e. file:///), since paths such as c:\dev, will pickup c: as the server causing the tests to fail.
- Just looks for the file name in traceback texts (e.g. *test_testrunner.lpy instead of /*/test_testrunner.lpy), otherwise it will fail because the output string will be c:\*\test_testrunner.lpy on windows.
The test suite currently fails to run because package dependencies have …
> Fix MS-Windows specific failures in test suite.

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
Hi,
can you please consider a patch to evaluate only the expression that matches the clause. It fixes #699 .
The issue was that `~(apply hash-map pairs)` evaluated all the clauses expressions.
With this update, the clauses are turned into `cond` clauses, taking extra case to quote any symbol bindings.
I tried to keep as match of the old code as possible, I could not think of any other way of doing so. It seems as if this requires a special form to as not to evaluate the clauses (e.g. `cond`). The drawback with this approach is that we went from O(1) to find the right expr to return it's value, to O(n).
Feel free to update or discard in case there is an obvious better solution.
I've included a test to confirm the same.
Thanks,
(the corresponding def in clojure-1.11 is [quite …
> `case` should only evaluate the matching clause expr

- CHANGELOG.md
- src/basilisp/io.lpy
- tests/basilisp/test_io.lpy
Hi,
can you please consider a fix for not dropping the first character of paths on MS-windows. It fixes #703.
This issue was introduced with a fix in #688 where the redundant first char should only be dropped from absolute paths.
I've added a test for the same.
Thanks
> Fix issue with relative MS-windows paths

- .prospector.yaml
- CHANGELOG.md
- src/basilisp/contrib/sphinx/domain.py
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
- tests/basilisp/test_core_macros.lpy
Hi,
could you please consider compatibility fix with Clojure for `(str nil)` to return the empty string. It fixes #706.
I have added a basic test for it and also corrected one that was inserting `nil` while concatenating strings.
I've also had to move `nil?` forward to use it in `str`.
Thanks
> Fix for (str nil) to return the empty string

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/runtime.py
- tests/basilisp/test_core_fns.lpy
Hi, 
could you please review fix for `sort` to support maps and boolean comparator fns. This completes #708.
I've also made some changes to the comments of the affected fns to indicate that we are now using the `compare` fn as default, but feel free to correct.
Tests for the same were also added.
Thanks
> Support `sort`ing of maps and boolean comparison fns.

- CHANGELOG.md
- src/basilisp/test.lpy
Hi,
could you please review patch to have `(is (= exp act)` evaluate its argument only once when failing. It fixes #712.
Previously, the arguments were evaluated once in the `when` close, and then once more in the `:actual` and `:expected` keys.
I haven't introduced a test case, because this issue manifest itself only when the test fails, which inadvertently will fail the test suite. Thus I was expecting perhaps you could reason about its behavior for the review? 
(Though now that I think of it, it might be possible to write a test case for the `gen-assert` multimethod  rather than the `is` case which will fail the test suite)
Here are the result running the same test in #712 with the fix, it only prints `:5` once as expected this time:
``` clojure
basilisp.user=> (require '[basilisp.test …
```
> Evalue (is (= exp act)) only once when failing the equality test

- CHANGELOG.md
- src/basilisp/lang/runtime.py
- tests/basilisp/test_core_fns.lpy
Hi,
could you please review patch to fix an issue with `sort-*` erroring out on an empty seq. Fixes #716.
It now returns an empty list in accordance with clojure
https://github.com/clojure/clojurescript/blob/e7cdc70d0371a26e07e394ea9cd72d5c43e5e363/src/main/cljs/cljs/core.cljs#L2467-L2479
I've included tests for the same.
Thanks
> Fixed issue with sort-* fns returning an error on empty seqs.

- CHANGELOG.md
- docs/requirements.txt
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/runtime.py
- tests/basilisp/test_core_fns.lpy
Hi,
could you please review patch to fix `intern`. It addresses #724.
It was using var methods such as `.set-root` that don't exist.
Tests included.
Thanks
> Adress issue with `intern` not working

- CHANGELOG.md
- src/basilisp/lang/runtime.py
- tests/basilisp/namespace_test.py
- tests/basilisp/test_core_fns.lpy
Hi can you please review patch to fix the problem of `ns` becoming unavailable after executing `in-ns` in the context of the `eval` operation. It addresses #718.
(part of breaking the individual bugfixes from #723)
thanks
> Fix issue with `ns` being unavail after `in-ns` during `eval` (#718)

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
Hi,
could you please review patch to fix issue with import name aliasing in the context of an `eval` operation. It addresses #719.
(part of breaking the individual bugfixes from https://github.com/basilisp-lang/basilisp/pull/723)
Thanks.
> Fixed issue with import modules aliasing using ns eval (#719)

- CHANGELOG.md
- src/basilisp/lang/runtime.py
- tests/basilisp/test_core_fns.lpy
Hi,
could you please consider patch to fix an issue with with `ns-resolve` erroring out on macros. It addresses #720.
(part of breaking the individual bugfixes from https://github.com/basilisp-lang/basilisp/pull/723)
Thanks
> Fixed issue with `ns-resolve` throwing error on macros (#720)

- CHANGELOG.md
- src/basilisp/stacktrace.lpy
- tests/basilisp/stacktrace_test.lpy
Hi,
could you please review patch to introduce a new namespace `basilisp.stacktrace` and a `print-cause-trace`. It partly addresses #721.
This is a requirement of the upcoming nbb nrepl-server port implemented in #723. CIDER specifically requests this function when an exception is thrown to display to the user, making it essential.
thanks
> Added rudimentary support for basilisp.stacktrace/print-cause-trace

- CHANGELOG.md
- src/basilisp/lang/atom.py
- src/basilisp/lang/reference.py
- src/basilisp/lang/runtime.py
Hi,
could you please review patch to fix what it seems to be a potential issue with how readwrite locks are used in basilisp. It addresses #722.
This was discovered while testing of the upcoming nrepl-server described in #723. The nrepl-server tests which are using threads were failing due to trying to release an rlock which has been already released, and is fixed as described in #722 by using `with self._lock.gen_rlock()` instead of a single instance of `with self._rlock()`. The error was
```
File "/home/runner/work/basilisp/basilisp/.tox/py39/lib/python3.9/site-packages/basilisp/lang/runtime.py", line 706, in find
return v
File "/home/runner/work/basilisp/basilisp/.tox/py39/lib/python3.9/site-packages/readerwriterlock/rwlock.py", line 49, in __exit__
self.release()
File …
```
> Fix issue with `readerwritelock` usage in basilisp (#722)

- CHANGELOG.md
- pyproject.toml
- src/basilisp/lang/compiler/__init__.py
> Deprecate `astor` for Python 3.9+

- CHANGELOG.md
- pyproject.toml
- src/basilisp/contrib/pytest/testrunner.py
- tests/basilisp/importer_test.py
- tests/basilisp/testrunner_test.py
- tox.ini
> Upgrade to using PyTest 7

- CHANGELOG.md
- src/basilisp/io.lpy
- tests/basilisp/test_io.lpy
Hi,
could you please review fix to make `basilisp.io/writer`'s :append true option working. It fixes #741.
I've also added some basic tests for it.
Thanks
> Fix issue with basilisp.io/writer :append failing

- src/basilisp/contrib/pytest/testrunner.py
- tests/basilisp/test_stacktrace.lpy
Hi, 
could you please review patch to fix a break with the  recent upgrade to pytest 7 in #738 in the circle CI coverage test. Fixes #740.
The `_test` suffix was not preperly identified as a basilisp test suffix, and was failing the coverage tests for `stacktrace_test.lpy`, which was not following the same pattern as of the other test files.
I've both fixed the testrunner to properly identifying these as before the upgrade, but also renamed the  above to `test_stacktrace.lpy` for conformity with the current pattern.
Thanks
> fix issue with _test filename suffix in pytest testrunner

- CHANGELOG.md
- src/basilisp/lang/keyword.py
- tests/basilisp/keyword_test.py
Hi,
could you please review patch to have keyword fn test for membership in sets. It fixes #762.
Thanks
> Keyword fn should test for membership in sets

- CHANGELOG.md
- src/basilisp/lang/runtime.py
- tests/basilisp/core_test.py
- tests/basilisp/test_core_fns.lpy
Hi,
could you please review compatibility patch with Clojure to make vars callable. It addresses #767.
I am not sure this if the `class Var` is the right place to make vars callable or the analyzer, which should expand them to a callable var value last node.
Nevertheless, I will kindly request your help with the type hinting, currently it will fail the linter with the following error
```
src/basilisp/lang/runtime.py:279:15: E1102: self.value is not callable (not-callable)
```
but not sure how to fix it, I've tried the class Var `value` property method to return a maybe Callable but it didn't work.
Thanks
> callable var

- CHANGELOG.md
- src/basilisp/lang/keyword.py
- tests/basilisp/keyword_test.py
Hi,
could you please review patch to fix an issue with keyword fns throwing a type error on vectors. Fixes #770.
thanks
> Fix issue with keyword fns erroring out on vectors

- CHANGELOG.md
- src/basilisp/lang/symbol.py
- tests/basilisp/symbol_test.py
Hi,
can you please review patch to add support for symbols as fns for maps and sets. Fixes #775.
Tests are copied from the corresponding call fn for keywords.
Thanks
> support symbols as fns for maps and sets

- CHANGELOG.md
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
> Fix a bug where deftype names could not be called if they contain a dash

- CHANGELOG.md
- src/basilisp/cli.py
- src/basilisp/lang/runtime.py
- tests/basilisp/cli_test.py
> Collect CLI arguments sent to `basilisp run` or Basilisp scripts

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
- tests/basilisp/test_core_macros.lpy
HI,
could you please review patch to treat the ampersand operator in macros as a standalone symbol. Fixes #772.
Test included.
thanks
> fixed issue with variadic ampersand symbol in macros

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/corpus/core_load_1.lpy
- tests/basilisp/test_core_fns.lpy
Hi,
could you please consider patch to adjust the `load` input path to be treated as relative to the current namespace or root path. It fixes #782.
I've also added a `corpus` directory in `tests/basilisp` so I can reference the input file. 
Thanks
> basilisp.core/load input path compatibility with clojure

- CHANGELOG.md
- src/basilisp/contrib/bencode.lpy
- src/basilisp/contrib/nrepl_server.lpy
- src/basilisp/lang/compiler/analyzer.py
- tests/basilisp/compiler_test.py
Hi,
could you please review patch to not work on unused bindings whose name begins with `_`. It addresses #756.
I've addressed some of such warnings coming up when running the nrepl-server, and added a test.
Thanks
> Do not warn on unused bindings whose names begin with _

- CHANGELOG.md
- src/basilisp/lang/compiler/generator.py
Remove code which generates an assignment to a name for `do*`, `let*` and `letfn*` forms which should significantly reduce the number of redundant assignments generated by the Basilisp compiler.
Fixes #799
> Improve Python generation for several special forms

- CHANGELOG.md
- src/basilisp/core.lpy
> Provide names for methods generated via `extend-type` and `extend-procol`

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
Hi,
could you please review patch to allow `case` to work with exclusive default expressions. Fixes #807.
This is also to maintain Clojure compatibility.
Thanks
> Permit default expresssions in `case` without clauses

- CHANGELOG.md
- docs/requirements.txt
- pyproject.toml
Attempt to fix #815.
There appears to be a recent new sphinx-apphelper version that is not compatible with sphinx 4.4.0?
deptree
``` 
basilisp==0.1.0b0
...
sphinx-rtd-theme==2.0.0
└── sphinxcontrib-jquery [required: >=4,<5, installed: 4.1]
└── sphinx [required: >=1.8, installed: 7.1.2]
├── alabaster [required: >=0.7,<0.8, installed: 0.7.13]
├── Babel [required: >=2.9, installed: 2.14.0]
├── colorama [required: >=0.4.5, installed: 0.4.6]
├── docutils [required: >=0.18.1,<0.21, installed: 0.20.1]
├── imagesize [required: >=1.3, installed: 1.4.1]
├── Jinja2 [required: >=3.0, installed: 3.1.3]
│   └── MarkupSafe [required: >=2.0, installed: 2.1.3]
├── packaging [required: >=21.0, installed: 23.2]
├── pygments [required: >=2.13, installed: 2.17.2]
├── requests [required: >=2.25.0, installed: …
```
> Pin sphinx applehelp version

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
Hi,
could you please review patch to dynamically bind core `pr` fn. It fixes #820.
Thanks
> Make `pr` a dynamic var

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/cli_test.py
- tests/basilisp/contrib/nrepl_server_test.lpy
- tests/basilisp/core_test.py
Hi,
can you please consider patch to emit OS specific line endings for print fns. It fixes #810.
thanks
> Emit OS specific line endings for `prn` and `println`

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
Hi,
could you please consider patch to accept any character by the reader as character literal. It fixes #816.
I've updated the test to include the new cases.
Thanks
> support any char in character literals

- tests/basilisp/cli_test.py
Hi,
could you please review patch to attempt to fix the intermittent failures of the nrepl server cli test on macos. It fixes #824.
It seems that the server has not been given the chance to write the port number to the newly created file, so it attempts to yield control back to the server.
Thanks
> Attempt to fix the intermittent test failures with nREPL on macos.

- .gitignore
- CHANGELOG.md
- src/basilisp/test.lpy
- tests/basilisp/testrunner_test.py
> Fix `basilisp.test/is` macro error reporting when used within macros

- .github/workflows/run-tests.yml
- CHANGELOG.md
- pyproject.toml
Hi,
could you please review proposal to have a CI test against checking the minimal support python and deps version can pass the test suite. It fixes #826.
The job is expected to fail the first time it runs, because attrs minimal version of 20.1.0 fails to bootstrap the tests, which is also proving the point of this patch.
It will subsequently be corrected to the next available version which will pass the test.
Thanks
> CI test for minimal python & deps versions support

- .github/workflows/run-tests.yml
There was an issue in #827 where subsequent runs of the minimum dependencies job would fail due to a missing Poetry binary. I believe the cause of that was a missing cache path. The cache paths were copied from the other `run-tests` job which was also wrong, but which did not ever try to execute `poetry` binary directly so the missing binary issue was never discovered.
> Store Poetry binary in the cache

- CHANGELOG.md
- docs/compiler.rst
- src/basilisp/cli.py
- src/basilisp/contrib/pytest/testrunner.py
- src/basilisp/lang/compiler/__init__.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/constants.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/seq.py
- src/basilisp/lang/typing.py
- tests/basilisp/compiler_test.py
- tests/basilisp/test_core_fns.lpy
Add a compile-time warning for arity mismatches on function invocations. The warning is enabled by default (if the dev logger is enabled and configured for at least `WARNING` level logs).
In order to facilitate this work, we also had to change the computation of the Basilisp function `arities` attribute set. Previously this included only fixed arities (the argument count for each non-variadic function arity) and a `:rest` keyword if the function included a variadic arity. Now `arities` will include all fixed arities including the number of fixed (non-variadic) arguments to the varidic arity. This allows for more sophisticated warnings.
As part of this bill of work, it was also required to update `partial` to support computing a new set of `arities` for partial applications. …
> Warn at compile time on arity mismatch for function invocation

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_multifn.lpy
Hi,
could you please consider support for optional metadata argument in `defmulti`. It fixes #857.
Added tests for the same.
Thanks
> Support for optional metadata defmulti argument

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- tests/basilisp/compiler_test.py
> Allow def names without reader metadata by default

- CHANGELOG.md
- src/basilisp/stacktrace.lpy
- tests/basilisp/test_stacktrace.lpy
> Add `basilisp.stacktrace` namespace

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
Hi,
could you please consider patch to support the Clojure's `*flush-on-newlne*` dynamic var. It fixes #865.
Although the corresponding documentation string in Clojure describes this variable as used [for flushing the stream everytime a newline is printed](https://github.com/clojure/clojure/blob/e3520c07e8b21dbf5a91fa14b7114b90dc1e89c6/src/clj/clojure/core.clj#L6540-L6544), it is only referenced by  `prn` to [flush its output after the last newline has been written](https://github.com/clojure/clojure/blob/e3520c07e8b21dbf5a91fa14b7114b90dc1e89c6/src/clj/clojure/core.clj#L3729-L3737). This patch follows the same logic.
Thanks
> *flush-on-newline* support

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
Hi,
can you please consider attempt to support binding destructuring in `for` bindings. It fixes #774.
Basically, it seems that destructuring support is not available because the general destruturing dispatch mechanism is not defined yet at the point when `for` is defined.
The idea with this patch is to rename the initial implementation as `for*` and redefine `for` later on after the destructuring dispatch mechanism is available and picked up for free.
Thanks
> `for` bindings destructuring support

- CHANGELOG.md
- docs/differencesfromclojure.rst
- docs/pyinterop.rst
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
Hi,
could you please consider patch to add `==` as an alias for `=`. Fixes #859.
I've also updated the doc to describe the difference of int vs float comparison in basilisp vs Clojure.
Thanks
> Added `==` as an alias for `=`

- CHANGELOG.md
- src/basilisp/lang/runtime.py
- tests/basilisp/runtime_test.py
Hi,
could you please consider patch to have `concat` on maps return k/v pairs instead of keys. It fixes #871.
The issue as I understand it that the underlying map library iterates over keys rather than k/v pairs, and thus it needs to be converted first to a sequence (which correctly converts map into a seq of pairs).
Thanks
> Fix issue with `concat` on maps returning keys instead of key/values

- docs/differencesfromclojure.rst
- src/basilisp/core.lpy
Hi, 
I've document the differences of the `int` and `float` functions from Clojure. It resolves #875.
Do we need a changelog entry for this?
Thanks
> document core int/float fns difference with clojure

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
Hi,
can you please consider patch to add support for Clojure's `fnext` fn. It resolves #879.
Thanks
> Add support for `fnext` core function

- CHANGELOG.md
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/keyword.py
- src/basilisp/lang/list.py
- src/basilisp/lang/map.py
- src/basilisp/lang/obj.py
- src/basilisp/lang/queue.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/set.py
- src/basilisp/lang/symbol.py
- src/basilisp/lang/vector.py
This PR introduces the `INamed` interface (similar to Clojure's `Named`) which is applied to the Keyword and Symbol classes. Having an interface for this allows us to perform type checking for relevant features (in particular, the existence of a name or namespace) without needing the import either class directly (thus avoiding circular dependencies).
I also added type annotations for the Lisp representation keyword arguments (which is a useful addition ahead of #882 merging).
Fixes #884
> Add `INamed` interface for Keywords and Symbols

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
Hi,
could you please consider fix for the issue with using the reader var macro in syntax quotes. It fixes #889 
I've also added a test.
Thanks
> Fix issue with syntax quoting reader var macro

- CHANGELOG.md
- src/basilisp/lang/obj.py
- tests/basilisp/cli_test.py
- tests/basilisp/importer_test.py
- tests/basilisp/lrepr_test.py
Hi,
could you please consider patch to have the `str` function on seq string items surrounding them with quotation marks. It fixes #891 
The fix simply resets the `human_readable` kw argument for inner elements to False for seqs and maps.
I have included a `test_str` test in `lrepr_test.py` to test the same. This is based on `test_lstr` above it.
It appears to me as if `test_lstr` is inaccurately named. Despite being labeled `lstr`, it employes `pr-str` which differs from invoking `lstr` directly with its arguments, Therefore, I find naming it `test_lstr` a little misleading; it rather seems as to be only capturing the output of `pr`. I could be wrong though 😅 
Thanks
> Fix where `(str seq)` was printing seq string items without `"`

- CHANGELOG.md
- src/basilisp/cli.py
- src/basilisp/lang/map.py
- src/basilisp/lang/obj.py
- src/basilisp/lang/runtime.py
- tests/basilisp/test_core_fns.lpy
Hi,
could you please review draft support for the *print-namespace-maps* dynamic variable. It resolves #882.
I implemented the support at the lowest `obj.py` level, though this required to bring in the `keyword.py` and `symbol.py` modules resulting to cyclic dependencies. Not sure how else to implement it, so any other suggestions are most welcome.
I've also blindly followed the example of *print-dup* on how I ended setup the variable in the cli/runtime/object .py files.
In addition, I've used a set to compare the printed output of the map result with multiple k/v, exhaustively covering the possible orderings, is there perhaps a better simpler way to do this? This currently is prune to user errors.
Thanks
> *print-namespace-maps* support

- CHANGELOG.md
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
Hi,
can you please review patch to fix issue with accessing interop properties when they match a builtins name. It fixes #896.
This seems like a simple fix to simply to ignore munging builtins names when accessing interop properties, it does not seem we want it to apply here.
I've also added a test.
Thanks
> Fix issue accessing prop with interop matching builtin name

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/prompt_test.py
- tests/basilisp/reader_test.py
- tox.ini
> Allow `.` characters in keyword names

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/exception.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/optimizer.py
- src/basilisp/lang/compiler/utils.py
- src/basilisp/prompt.py
MyPy 1.11 seems to have greatly improved its ability to type check, but that also revealed a huge number of issues in the type hints used in the compiler. This PR fixes those type hints (hopefully).
> Fix type checking errors from MyPy 1.11

- CHANGELOG.md
- src/basilisp/cli.py
- tests/basilisp/cli_test.py
Hi,
could you please review patch to convert cli run paths to posix. It fixes #912.
The path was passed verbatim to `load` and MS-Windows path separator chars `\` was treated as escape sequences.
The fix also checks if path refers to a real file, so that it avoids forming invalid `load` requests.
Tests updated.
Thanks
> Fix bug with `cli run` failing on MS-Windows file paths

- CHANGELOG.md
- Makefile
- docs/cli.rst
- docs/concepts.rst
- docs/conf.py
- docs/requirements.txt
- pyproject.toml
- src/basilisp/contrib/bencode.lpy
- src/basilisp/contrib/nrepl_server.lpy
- src/basilisp/core.lpy
- src/basilisp/json.lpy
* Added [`sphinx-autobuild`](https://github.com/sphinx-doc/sphinx-autobuild) to improve documentation development flow
* Added [`sphinx-copybutton`](https://github.com/executablebooks/sphinx-copybutton) and [`sphinxext-opengraph`](https://github.com/wpilibsuite/sphinxext-opengraph) extension to the Read the Docs build
* Updating tons of references across the entire codebase to the official Python documentation using [`intersphinx`](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) (added in #909)
> Minor documentation fixes

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
> Coerce booleans using Basilisp's rules, not Python's rules

- CHANGELOG.md
- src/basilisp/lang/seq.py
- tests/basilisp/runtime_test.py
- tests/basilisp/seq_test.py
Fixes #936 
Another fix related to #934
> Fix thread-safety for sequences wrapping Python Iterators

- docs/cli.rst
- docs/repl.rst
Hi,
I have updated the nREPL server documentation in the `cli` section to provide new instructions on how users can start the server for their editor.
Additionally, I've a reference to it in the `REPL` page, so users whoa re likely to be looking for the nREPL server, can locate it more easily. I consider promoting the nREPL section to a new page next to `REPL`, but decided to be discreet for now.
Any feedback would be greatly appreciated.
Thanks
> Update nREPL server doc with supported and unsupported editors

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/seq.py
- tests/basilisp/test_core_fns.lpy
-  `ISeq` now inherits from `IPersistentCollection` so that `coll?`, `empty`, and `conj` now work for sequences.
- Added trivial arities for `conj` as in Clojure
These changes match the behaviour of Clojure types and functions
> Make lazy sequences collections.

- CHANGELOG.md
- src/basilisp/cli.py
- tests/basilisp/cli_test.py
This PR does provide a solution to the immediate problem described in #957 which prevents running namespaces from the CLI in many cases, however it does not address the larger Clojure compatibility issue outlined in the ticket.
> Fix a bug where Basilisp would error running a namespace from the CLI

- CHANGELOG.md
- src/basilisp/test.lpy
- tests/basilisp/testrunner_test.py
Hi,
could you please consider patch to correct the reporting on the expected outcome of `basilisp.test/is` when expr falls in the :default handling.  It fixes #965.
I've included a test case for a function call expr, even though there was a case for `(is false)` which I've also updated.
Thanks
> Fix issue with `test/is` expected value misreporting on failure

- tests/basilisp/testrunner_test.py
Hi,
can you please consider follow up patch to #966 to disable a testrunner test that fails intermittently on PyPy3.9 because it produces a traceback line number which is erroneous. This doesn't appear to be an issue with Basilisp, but rather with that particular version of PyPy.
I've also removed an if else block in the same which appear to me to be redundant, both if/else blocks were doing the same.
I can see the test in question did not run on my circle ci run.
Thanks
> Disable testrunner test for pypy-3.9 which produces erroneous behvr

- CHANGELOG.md
- Makefile
- src/basilisp/contrib/nrepl_server.lpy
- tests/basilisp/contrib/nrepl_server_test.lpy
Hi,
could you please consider patch to improve on the nREPL server exception messages, inline with what has been done for the REPL recently. It addresses #968.
Tests updated to reflect the new exc messages.
I've also in-lined the logger functions to be  closer to the actual logging interface, and added a new target in the markefile for easier debugging.
Thanks
> Improve on nrepl exception formating and logging interface

- src/basilisp/core.lpy
Seems like a goof from #961 where I had a duplicate definition of `spit` and `slurp`.
> Remove duplicate definition of spit and slurp

- CHANGELOG.md
- pyproject.toml
- src/basilisp/lang/atom.py
- src/basilisp/lang/reference.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/util.py
- tests/basilisp/compiler_test.py
- tests/basilisp/lrepr_test.py
- tests/basilisp/reader_test.py
- tox.ini
Remove some lightly used dependencies and replacing them with stdlib replacements: 
- `python-dateutil` was only used for parsing `#inst "..."` tags, which was already supported via `datetime.datetime.fromisoformat`, so removing it for now.
- `readerwriterlock` was intended to be a reader-preferring lock for things like Atoms, but it's not been updated in some time and probably wasn't making much of a difference to begin with since Python still has a GIL.
> Remove `python-dateutil` and `readerwriterlock` dependencies

- CHANGELOG.md
- docs/concepts.rst
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/constants.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- tests/basilisp/compiler_test.py
- tox.ini
> Allow artificial abstractness to take precedence over true abstractness for `deftype*` and `reify*`

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
Hi,
could you please consider patch to fix the inconsistent behaviour of the `basilisp.core/with` `body` argument. It fixes #981.
Tests added.
Thanks
> Fixed inconsistent behaviour with basilisp.core/with body

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
> Return last evaluated from load functions

- CHANGELOG.md
- src/basilisp/contrib/nrepl_server.lpy
- src/basilisp/core.lpy
> Add read-all function

- CHANGELOG.md
- docs/reader.rst
- src/basilisp/cli.py
- src/basilisp/core.lpy
- src/basilisp/lang/reader.py
- src/basilisp/test/fixtures.lpy
- tests/basilisp/reader_test.py
- tests/basilisp/test_data_readers.lpy
Fixes #924 
Hello,
I managed to get the custom data readers feature implemented. Let me know if you have any question or would like to see any changes.
Core Changes:
- Added custom data readers, from files on the path as well as entry points.
- Entry point groups can be customized or disabled with cli arguments
- Added `*default-data-reader-fn*`
- Changed the reader to allow any tag values like in Clojure, but restrict tags from loaded data readers to only qualified symbols.
- Updated documentation with new features
Other Changes:
- Changed load functions to return the result of the last form evaluated as in Clojure. I was touching this function anyway and noticed the discrepancy.
- Added `basilisp.core/read-seq`; it allows other namespaces to stop depending on `basilisp.lang.reader` …
> Add custom data readers #924

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
Hi,
can you please consider patch to address an issue with `basilisp.core/time` failing when called outside of the core ns. It fixes #991.
Added test for the same.
I've also wrapped the `expr` in a `do` block so that it can't interfere with the out `try block` thanks.
Thanks
> Fixed issue with `basilisp.core/time` failing outside of core

- CHANGELOG.md
- src/basilisp/lang/promise.py
- tests/basilisp/promise_test.py
Hi,
can you please consider patch to notify all waiting threads for a promise delivery. It fixes #993 
This patch addresses the issue where one or more threads waiting for the delivery condition in `Promise.deref` were not being notified upon the delivery. In the worst-case scenario, this could lead to threads deadlocking while waiting indefinitely for the notification, or in the case of a timeout, returning only after the timeout has expired.
I've added a test based on the originally reported scenario that checks how long it takes for the delivery to be received.
The time it now takes for the original case to be notified of the delivery is just above the sleep time of the secondary thread at 0.108 secs
```clojure
basilisp.user=> (import threading) (import time)
<module 'time' (built-in)> …
```
> Notify all waiting threads on a promise delivery

- CHANGELOG.md
- src/basilisp/lang/keyword.py
- tests/basilisp/keyword_test.py
Fixes #997 
Quick fix. I noticed that using a keyword as a function with `nil` as the collection always returns `nil` rather than the default. 
This demonstrates the bug:
```clojure
(:foo nil :bar)
;; Expected 
=> :bar
;;Actual
=> nil
```
> keyword function return default in error cases

- src/basilisp/core.lpy
- tests/basilisp/test_data_readers.lpy
This is an amendment for #979. 
This was missed when merging back #986 after it was separated out.
> Use *default-data-reader-fn* when calling core read functions #924

- CHANGELOG.md
- src/basilisp/contrib/nrepl_server.lpy
- tests/basilisp/contrib/nrepl_server_test.lpy
Hi,
can you please review patch to let nREPL server to exit even when client connections are still open. It addresses #1002.
This is simply done by setting the server's `daemon-threads` field to true.
Additionally, I've updated the `:server*`  option accepted by  `server-make!` from an `atom` to a `promise`. This change aligns with the original intent of providing a server reference when it becomes available. Note that this is a breaking change as it alters the API. Given the current development stage and no known users of this API, I believe it's safe to include this change now. Let me know if you'd prefer this in a separate PR or think otherwise.
I've added a test for the same.
Thanks
> ensure nREPL server can exit even when client connections are open

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/runtime.py
- tests/basilisp/contrib/nrepl_server_test.lpy
- tests/basilisp/test_core_fns.lpy
Hi,
could you please consider patch to update the `basilisp.core/deref` timeout argument to us ms instead of secs. It addresses #1007 
This is to align with the same in `clojure.core/deref`.
I have add a `promise` basilisp test and updated an existing `future` one. The tests check that the timeout for an unfulfilled promise returns within a range of 100ms. I believe this range provides sufficient buffer to avoid interference from parallel processing on the host.
Thanks
> Align `basilisp.core/deref` with Clojure to use timeout in ms

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
> Don't obscure exceptions occuring during inlining in macroexpansion

- src/basilisp/lang/compiler/analyzer.py
Fixes #1013 (second case I missed the first time around)
> Don't obscure inlining cause exceptions

- CHANGELOG.md
- src/basilisp/contrib/nrepl_server.lpy
- src/basilisp/core.lpy
- src/basilisp/lang/reader.py
- tests/basilisp/contrib/nrepl_server_test.lpy
- tests/basilisp/reader_test.py
- tests/basilisp/test_core_fns.lpy
Hi,
could you please consider patch to pass the nREPL client's eval file line and column numbers down to the reader for more accurate compiler exception reporting. It fixes #1037.
I have attempted a focused approach to propagate the line and column parameters to the error reporting mechanism. If this approach is not optimal, I am open to reorganizing the code based on better suggestions.
I've included tests down the affected path to cover these changes.
Thanks
> Pass nREPL client evaled code's line and col nums to the reader

- tests/basilisp/cli_test.py
No functional changes. Just moving the tests that already exist into nested subclasses based on the particular "form" of `basilisp run` that each is testing (e.g. code string, file, stdin, or namespace).
> Refactor CLI run subcommand tests into nested classes for organization

- CHANGELOG.md
- docs/cli.rst
- docs/reader.rst
- docs/runtime.rst
- src/basilisp/cli.py
- tests/basilisp/cli_test.py
> Allow adding additional `sys.path` entries from the CLI

- CHANGELOG.md
- src/basilisp/lang/source.py
- tests/basilisp/source_test.py
Hi,
could you please review patch which checks for a newer version of a source file when formatting the source context. It fixes #1042.
I've made the check a permanent feature rather than an option passed to `format_source_contest`, as I couldn't think of a scenario where using the cached version would be preferable if the file had been modified (but I could be wrong).
Added a test to cover this case.
Thanks
> Check for updated source file when formating source

- CHANGELOG.md
- src/basilisp/cli.py
- src/basilisp/logconfig.py
- src/basilisp/main.py
> Add CLI arguments for enabling the development logger and setting logging level

- CHANGELOG.md
- docs/compiler.rst
- src/basilisp/importer.py
- tests/basilisp/importer_test.py
> Respect Python bytecode generation settings

- .gitignore
- CHANGELOG.md
- docs/runtime.rst
- pyproject.toml
- src/basilisp/cli.py
- src/basilisp/core.lpy
- src/basilisp/io.lpy
- src/basilisp/lang/compiler/__init__.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/constants.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/optimizer.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
> Emit warnings when requiring or importing with an already used alias

- CHANGELOG.md
- pyproject.toml
- src/basilisp/core.lpy
- src/basilisp/importer.py
- src/basilisp/lang/runtime.py
- tests/basilisp/importer_test.py
> Support reloading namespaces

- CHANGELOG.md
- docs/runtime.rst
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/__init__.py
- tests/basilisp/compiler_test.py
Fixes #1028 
`do` forms emitted by macros are still not completely unrolled.
> Unroll top-level `do` forms

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
Hi,
can you please a fix for the line number in the metadata generated by the reader. It fixes #1063.
We now check the char at -2 only if it’s:
-  `\n` (for `\nC` or `\r\nC` case)
-  `\r` (for the `\rC`, but not `\r\n`, case).
where `C` is any other char.
Added tests for the same.
Thanks
> Fix a bug where the reader was double counting the CRLF newline seq

- CHANGELOG.md
- src/basilisp/contrib/nrepl_server.lpy
- tests/basilisp/contrib/nrepl_server_test.lpy
Hi,
could you please review patch to align the nrepl server's `info` op with the `cider-nrepl` spec. It fixes #1066.
According to the spec,  the `:file` return value should be a URI when it refers to an absolute path. It also specifies `:column` as a return key, which was previously missing.
`cider-nrepl` `info` spec: https://docs.cider.mx/cider-nrepl/nrepl-api/ops.html#info
The  nrepl-server's `info` test has been updated accordingly.
Thanks
> conform to spec on nrepl's info op on :file and :column values

- CHANGELOG.md
- src/basilisp/test.lpy
- tests/basilisp/contrib/nrepl_server_test.lpy
- tests/basilisp/test_test.lpy
I've separated out the test fixture functions from #1044 for #980
> Add fixture functions to `basilisp.test` #980

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
> Add importing-resolve function to dynamically import Python names

- CHANGELOG.md
- src/basilisp/edn.lpy
- tests/basilisp/test_edn.lpy
> Fix double quote encoding in `basilisp.edn/write-string`

- CHANGELOG.md
- src/basilisp/prompt.py
This is a very helpful feature I noticed on the Clojure REPL and prompt-toolkit supported it natively, so it was a no brainer to add.
> Add support for highlighting closing parens, brackets, and braces at the REPL

- CHANGELOG.md
- docs/gettingstarted.rst
- docs/testing.rst
- src/basilisp/cli.py
> Add an empty entry to sys.path for basilisp test CLI subcommand

- docs/concepts.rst
I was reading the docs and noticed a couple sentences where it looked like the word "can" seemed appropriate.
> add "can" in a couple places

- CHANGELOG.md
- src/basilisp/contrib/pytest/testrunner.py
Hi,
can you please review patch to address the `basilisp test` failure on MS-Windows. It fixes #1080.
The problem arises because pytest's mechanism for capturing standard streams during tests breaks when those streams are saved before pytest.main is called and then used in the test. This happens when running `basilisp test` from the CLI:
In `basilisp.init`, `sys.stdout` and `sys.stderr` are saved to the `*out*` and `*err*` dynamic variables before `pytest.main` is called. If a test prints anything, it tries to write to these original streams, causing failures due to an issue I just reported in https://github.com/pytest-dev/pytest/issues/12876.
This patch rebinds `*out*` and `*err*` to the streams set by `pytest` and restores them when `pytest` finishes (via the `configure` functions). …
> Fix issue with `basilisp test` standard streams output

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- tests/basilisp/compiler_test.py
> Fix a bug referencing imported Python names containing dashes in place of underscores

- CHANGELOG.md
- src/basilisp/lang/obj.py
- src/basilisp/lang/runtime.py
- tests/basilisp/test_core_fns.lpy
- tox.ini
Hi,
could you please review patch to set the `*print-length*` default to `nil` instead of 50. It addresses #1093.
I’ve also added a docstring  (feedback welcome!) and a test.
Thanks
> Set *print-length* default value to nil instead of 50

- CHANGELOG.md
- src/basilisp/importer.py
fixes #1097 
I'm not sure if this is the extent of changes that need to occur, but I've been using these changes locally to start porting [portal](https://github.com/djblue/portal) and it's been working for me.
> Add support for cljc files

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
> Support reducing Records by `reduce-kv`

- CHANGELOG.md
- src/basilisp/cli.py
> Fix CLI test argument parsing

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
Fixes #1129 
For anyone who finds this PR (perhaps triaging a bug introduced by it in the future): I tried to ascertain exactly what Clojure JVM does in this situation and it is quite unclear in the reader code and not (at the time of writing) specified on any of the official documentation. Examples given there seem to indicate that fully qualified tags be given in `data_readers.cljc` and thus symbol resolution should not be performed on them, but they don't say explicitly. CLJS  `#js []` literals work as they do now in this PR so I'm going to assume this is the intended behavior.
> Do not attempt to resolve symbols in data reader tags

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/runtime.py
- tests/basilisp/test_core_fns.lpy
> `keyword` and `symbol` functions should treat strings as potentially namespaced

- CHANGELOG.md
- docs/reader.rst
- src/basilisp/core.lpy
- tests/basilisp/test_data_readers.lpy
Hi,
could you please review patch to only have the custom data reader loader only considers up to the first level subdirectories in the `sys.path` entries. It addresses #1135.
I've used transducers to improve performance, which required moving the custom data loaders code further down the namespace. The only function that changes is `data-readers-files`, which now only processes the top directory and immediate subdirectories.
I've adjusted the a test not to expect any readers to be found further down the subdirectories, andfixed a test which should have referred to `test/test`5`. 
I've also updated the documentation to indicate the change in behavior.
Thanks
cc @mitch-kyle
> custom data readers loader should not recurse further than first subdirectories of sys.path

- CHANGELOG.md
- src/basilisp/lang/runtime.py
- tests/basilisp/runtime_test.py
> Fix a bug where integer results of integer division are always returned as fractions

- CHANGELOG.md
- src/basilisp/core.lpy
Hi,
could you please consider patch to use an auto-gensym for the let binding in the `time` macro. It addresses #1143.
I assumed here that  a straight let binding was used inadvertently rather than an auto-gensym.
No tests were included due to the simplicity of the fix.
Thanks
> Fix issue with `time` failing to expand with `macroexpand-all`

- CHANGELOG.md
- Makefile
- docs/api/process.rst
- src/basilisp/process.lpy
- tests/basilisp/test_process.lpy
> Add the `basilisp.process` namespace

- .github/workflows/pypi-release.yml
Looks like I used a mix of the generic `release/v1` and specific version ref.
> Fix PyPI publishing action ref

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
> Fix a bug where `#` characters were not legal in keywords and symbols

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
> Fix a bug with seqs in matching clauses of the `case` macro

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/testrunner_test.py
> Support the optional `attr-map?` on the `ns` macro

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/compiler_test.py
- tests/basilisp/reader_test.py
> Fix a bug with syntax quoted anonymous functions

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
> Add support for pre- and post-conditions on fn forms

- CHANGELOG.md
- docs/compiler.rst
- docs/differencesfromclojure.rst
- src/basilisp/core.lpy
- src/basilisp/lang/runtime.py
- tests/basilisp/test_core_fns.lpy
- tests/basilisp/var_test.py
Hi,
can you please review change to have have `alter-var-root` to return the new value. It addresses #1166.
I've also updated various part of the documentation to note the effect of direct linking on this fn.  Please feel free to adjust partially or completely.
I've also added test cases for the `alter-var-root` for the new change plus to demo the direct linking behavior.
Thanks
> Update alter-var-root to return new val, updated docs

- CHANGELOG.md
- src/basilisp/core.lpy
Hi,
can you please review patch to have `import` to return `nil`. It addresses #1174.
I haven't included a test for this case, nor mentioned it in the docstring, implying the return value is unspecified. I'm not sure this is something we want to fix at the API level (although I did request it as an aesthetic addition).
> return nil from `import`

- tests/basilisp/test_core_fns.lpy
Hi,
can you please review to increase the lower bounder tolerance for the `future` `deref` test with a timeout period. It addresses #1184.
The samples for the CI test failures suggested that the failures had an error of -4ms, so I've increased the lower boundary to 95ms from 100ms. If this proves to be insufficient, I will further increase it to 90ms.
I've also corrected the labelling from `ms` to `s` (for seconds), the unit `perf-counter` returns.
I have not included this in the CHANGELOG, since I think is not required.
> Increase lower bound tolerance of future deref timeout test

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
Hi,
can you please review patch to merge the `attr-map?` and the metadata in `defn` using a `loop` rather than `conj`. It addresses #1186.
The previous `conj` operation was return in a list rather than a map. This also appears to be the likely cause why the `:decorators` meta key didn't work when passed in as `defn` metadata in `defasync`.
I've updated the test suite for the same.
Thanks
> Ensure `defn` metadata are always preserved as a map

- CHANGELOG.md
- docs/pyinterop.rst
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
Hi,
could you please review patch to support the `:decorators` key in anonymous `fn`s. It addresses #1178.
The handling of  `:decorators` has been nmoved to `fn`, which also ensures that the meta key is now considered when passed as  metadata to the `defn` name. This enables  support for supporting the meta key in `defn` derived macros such as `defasync`, as intended.
I've updated the `defn` docstring to hint that the processing is now done by `fn` now. 
I've also added tests for `fn`, `defn` and `defasync`, along with a section in the python interop doc about it.
Thanks
> Adds support for :decorators in anon fns, defasync

- CHANGELOG.md
- docs/testing.rst
- src/basilisp/contrib/pytest/testrunner.py
- src/basilisp/importer.py
- src/basilisp/lang/compiler/__init__.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/runtime.py
- tests/basilisp/testrunner_test.py
Possible alternative solution to #1165 and #1155
This PR changes the Python `importlib` machinery for Basilisp to simply focus on importing modules, without getting itself too mixed up in the business of figuring out what a namespace is actually _called_ from the module name. When `importlib.import_module` is called, Basilisp just figures out the location of the module on disk and starts loading it up as if it were a Basilisp module. It sets the newly introduced `basilisp.core/*import-module*` dynamic Var to the value of the importing module and lets the Basilisp runtime fetch that value down and attach it to a new namespace if and when it is appropriate to do so.
There may be some unintended side effects here for strange cases, so noting those here for now:
* If multiple namespaces are …
> Switch Python import machinery to focus primarily on Python modules

- CHANGELOG.md
- src/basilisp/process.lpy
- tests/basilisp/test_process.lpy
> Fix a bug with inherited stdout in `basilisp.process/exec`

- docs/pyinterop.rst
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
Hi,
can you please consider the follow up patch for anonymous fn decorators support (#1189). 
- Moved the note in python interop decorators doc at the top, as it contains important policy information.
- Updated the `fn` docstring to document the form/name metadata precedence rules established in #1189, where `name` metadata takes precedence over `form`.
- Added new test to verify precedence rule.
-  Corrected a test that was mistakenly using `defn` instead of `fn`.
I don't think this requires a changelog entry but I can add if necessary.
Thanks
> follow up patch to fn :decorators support, minor doc and test update

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
> Fix a bug where `condp` could throw an exception in some cases

- CHANGELOG.md
- src/basilisp/cli.py
- src/basilisp/contrib/pytest/testrunner.py
- tests/basilisp/testrunner_test.py
Hi,
could you please review patch to fix a likely regression issue where the testrunner couldn't handle relative paths in `sys.path`. It fixes #1204.
This is likely a regression from #1176, where the update to the new module loading system caused relative paths to never match a fully qualified module name. The patch now expands relative paths to their absolute form before comparing them to the module path.
This issue was breaking the vanilla `basilisp test` command, as it adds an empty string (`""`) entry to `sys.path`, which is interpreted as `"."`. Since this is a relative path, it wasn’t handled by the logic, causing the project directory not to be recognized as the root of the Basilisp test modules.
I’ve added a test that invokes `basilisp test` directly as a subprocess. …
> fix testrunner to handle relative entries in sys.path

- CHANGELOG.md
- src/basilisp/cli.py
- src/basilisp/lang/compiler/__init__.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/runtime.py
- src/basilisp/process.lpy
- tests/basilisp/test_process.lpy
> Fix deadlock on large output from `basilisp.process/exec`

- CHANGELOG.md
- pyproject.toml
- src/basilisp/cli.py
- src/basilisp/main.py
- tests/basilisp/cli_test.py
- tests/conftest.py
- tox.ini
Hi,
could you please review patch to pickup the boostrap site-packages location from the `sysconfig` `purelib` path. It fixes #1208.
The bootstrap options and code now operate on a single path instead of a list, likely because `getsitepackages` previously returned a list of paths, which is no longer relevant (unless there's another reason I'm missing).
I've also updated the `bootstrap` command to print the file's creation path, which I find useful for awareness.
For testing, I couldn't think of a case other than creating a virtual environment to test the `bootstrap` within it. I implemented a minimal solution using the `pytest_virtualenv` plugin, which provides a fixture for this. Since creating a Basilisp environment takes 20+ seconds, I added a pytest decorator to run it only on GitHub …
> Pickup bootstrap site-packages location from sysconfig purelib path

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- tests/basilisp/compiler_test.py
> Fix defining async generators

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
> Suppress successive forms with stacked `#_` reader macros

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_async_macros.lpy
> Support `async for` and `async with` constructs using macros

- CHANGELOG.md
- docs/pyinterop.rst
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
- tests/basilisp/namespace_test.py
> Add support for referring imported names

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
- tests/basilisp/test_protocols.lpy
> Fix multiple small bugs in `basilisp.core`

- CHANGELOG.md
- docs/pyinterop.rst
- src/basilisp/contrib/nrepl_server.lpy
- src/basilisp/contrib/sphinx/autodoc.py
- src/basilisp/contrib/sphinx/domain.py
- src/basilisp/core.lpy
- src/basilisp/lang/map.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/seq.py
- src/basilisp/lang/vector.py
- tests/basilisp/seq_test.py
- tests/basilisp/test_core_fns.lpy
- tests/basilisp/test_defrecord.lpy
Hi, 
could you please consider patch to remove explicit support of single-use iterables in sequences. It fixes #1192.
single-use iterables now throw a `TypeError`, when they are implicitly or explicitly coerced into a sequence. A new `iterator-seq` is introduced to explicitly convert them into a seq instead . See https://github.com/basilisp-lang/basilisp/pull/1198#issuecomment-2810302395 for the rationale. 
The `count` fn was also updated to behave the same.
There were a few places where single use iterators were converted implicitly to a seq, which are now explicitly converted using a `iterator-seq` or the python equivalent instead.
Tests are added for the same, as well as documentation section under Python Iterators.
Thanks
> Make support for single-use iterables explicit

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
**Update1**: this PR was repurposed to focus on optimizing to seq-consuming library functions to coerce their inputs into seqs before operating on them. It fixes #1234. 
Support generators in seq-consuming functions via the `when-let [coll (seq coll)]` idiom where applicable. Fixes #1192
> optimize seq-consuming library functions

- docs/pyinterop.rst
Hi,
Could you please consider a patch to add documentation for Python slicing? This has come up a few times in Discussions, and without guidance, it might take users a while to understand how slicing is achieved in Basilisp.
Thanks
> Add Python Slicing documentation entry

- src/basilisp/core.lpy
`identity` should be faster than `some?`
> Replace `every? some?` with `every? identity`

- CHANGELOG.md
- docs/pyinterop.rst
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
Hi,
can you please consider patch to introduce the `aslice` macro in `basilisp.core`. It addresses #1248.
Thanks
> Added `aslice` macro

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_async_macros.lpy
Hi,
can you please review patch to rename the `awhile` and `afor` macros to `while-async` and `for-async` for better clarity. It addresses the point about naming in #1248.
I felt placing `async` after `for`/`while` reads more naturally, but I'm open to other suggestions if you think a better naming.
Thanks
> rename awhile, afor to while-async, for-async

- tests/basilisp/compiler_test.py
Hi,
can you please consider patch to fix the following test warning. It ensures the async generator is properly closed by completing the `async for` loop.
thanks 
```
========================================== warnings summary ===========================================
tests/basilisp/compiler_test.py::TestFunctionDef::test_multi_arity_meta
/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py:744: RuntimeWarning: coroutine method 'aclose' of '__unique_kdghii_1104' was never awaited
self._ready.clear()
Enable tracemalloc to get traceback where the object was allocated.
See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
-- Docs: …
```
> fix async test warning

- CHANGELOG.md
- docs/gettingstarted.rst
- src/basilisp/main.py
- tests/basilisp/cli_test.py
> Synchronize `basilisp.main.init` to allow repeat invocations

- docs/pyinterop.rst
I find the initial writeup a bit terse, and also not clear and somewhat confusing for me. I hope you will accept this edit; I think this is an improvement, and helps elucidate and call out the one thing that confused me: namely, how referencing stuff within a class effectively creates its own namespace, something that took this used-to-Clojure brain some time to grok (making this PR was also part of my process).
Thank you for Basilisp!
> docs/pyinterop.rst: elucidate syntax around referencing things within modules

- docs/pyinterop.rst
This is a refinement (plus correction; apologies for missing that!) to my last PR (#1263)
> docs/pyinterop.rst: refine, + correct class-var reference

- .github/workflows/pypi-release.yml
- .github/workflows/test-pypi-release.yml
* Add a step to the release pipeline to publish sigstore signed artifacts to the associated Github Release.
* Add a Test PyPI release job which runs on merge to `main`.
> Publish artifacts to Github Release
