basilisp-lang/basilisp

- MANIFEST.in
- basilisp/__version__.py
- setup.py
Use the recommended `setup.py` script from [here](https://github.com/kennethreitz/setup.py).
Fixes #32
> Fix setup.py

- basilisp/compiler.py
- basilisp/core/__init__.lpy
- basilisp/lang/list.py
- basilisp/lang/map.py
- basilisp/lang/runtime.py
- basilisp/lang/seq.py
- basilisp/lang/typing.py
- basilisp/reader.py
- tests/compiler_test.py
- tests/list_test.py
- tests/map_test.py
- tests/reader_test.py
> Fix syntax quote

- basilisp/compiler.py
> Emit let binding AST nodes in proper order

- basilisp/lang/runtime.py
- basilisp/lang/seq.py
> Add meta fields to Cons cells

- basilisp/core/__init__.lpy
> Pass along form meta for fn macro

- Pipfile
- Pipfile.lock
- basilisp/lang/list.py
- basilisp/lang/map.py
- basilisp/lang/runtime.py
- basilisp/lang/seq.py
- basilisp/lang/set.py
- basilisp/lang/vector.py
- setup.py
- tests/list_test.py
- tests/map_test.py
- tests/set_test.py
- tests/vector_test.py
> Remove wrapt.ObjectProxy for collection types

- basilisp/compiler.py
- basilisp/core/__init__.lpy
- basilisp/importer.py
- basilisp/lang/runtime.py
> Update basic functions to use Python functions

- basilisp/compiler.py
- tests/compiler_test.py
> Add throw special form

- basilisp/util.py
- tests/munge_test.py
> Disallow Python keywords in munged strings

- basilisp/compiler.py
- basilisp/lang/util.py
- basilisp/reader.py
- tests/reader_test.py
> Use `sym#` syntax to generate new symbol in syntax quote

- basilisp/lang/runtime.py
- tests/compiler_test.py
- tests/reader_test.py
> Resolve symbols with current namespace if no namespace given

- basilisp/compiler.py
- basilisp/lang/util.py
- basilisp/util.py
- tests/munge_test.py
> Add a kwarg to munge to disallow builtins in munged names

- basilisp/compiler.py
- basilisp/importer.py
- basilisp/lang/runtime.py
- basilisp/lang/symbol.py
- basilisp/lang/util.py
- basilisp/main.py
- tests/compiler_test.py
- tests/core_test.py
- tests/munge_test.py
> Re-working import logic and symbol table

- basilisp/compiler.py
- basilisp/core/__init__.lpy
- tests/compiler_test.py
> Support functions of multiple arities in compiler

- basilisp/lang/seq.py
- tests/runtime_test.py
> Test some basic runtime functions

- basilisp/lang/seq.py
- tests/seq_test.py
> Add tests for the seq module

- basilisp/compiler.py
- tests/compiler_test.py
> Fix issue where AST could be generated twice, causing mismatches

- basilisp/core/__init__.lpy
- basilisp/lang/exception.py
- basilisp/lang/runtime.py
- tests/core_test.py
> Create a basic exception type

- basilisp/compiler.py
- basilisp/core/__init__.lpy
- tests/compiler_test.py
> Fix truthiness tests in if statements

- basilisp/lang/list.py
- basilisp/lang/vector.py
- tests/list_test.py
- tests/vector_test.py
> Return List and Vector when slicing List and Vector

- basilisp/lang/runtime.py
- basilisp/lang/seq.py
- tests/seq_test.py
> Cache sequence results

- basilisp/compiler.py
- basilisp/core/__init__.lpy
- basilisp/lang/runtime.py
- tests/compiler_test.py
- tests/core_test.py
- tests/runtime_test.py
> Non-stack consuming recursion using recur form

- basilisp/compiler.py
- basilisp/lang/associative.py
- basilisp/lang/map.py
- basilisp/lang/runtime.py
- basilisp/lang/vector.py
- tests/map_test.py
- tests/runtime_test.py
- tests/vector_test.py
This PR is a critical component of #91
> Add Associative ABC and apply to Map and Vector

- basilisp/compiler.py
- basilisp/lang/runtime.py
> Store generated Python code in `*generated-python*` in current ns

- basilisp/lang/collection.py
- basilisp/lang/list.py
- basilisp/lang/map.py
- basilisp/lang/runtime.py
- basilisp/lang/set.py
- basilisp/lang/vector.py
- tests/list_test.py
- tests/map_test.py
- tests/runtime_test.py
- tests/set_test.py
- tests/vector_test.py
This PR is a critical component of #91
> Add Collection ABC and conj

- basilisp/compiler.py
- tests/compiler_test.py
> Fix recur-in-tail-position checks for let bindings and macros

- basilisp/compiler.py
- basilisp/core/__init__.lpy
- basilisp/lang/runtime.py
- tests/compiler_test.py
- tests/runtime_test.py
> Recur correctly handles variadic arg lists

- basilisp/lang/seq.py
- tests/seq_test.py
> Lazy sequences and tests

- basilisp/reader.py
- tests/reader_test.py
> Allow arithmetic symbols in the reader

- basilisp/core/__init__.lpy
- basilisp/lang/atom.py
- basilisp/lang/delay.py
- basilisp/lang/deref.py
- basilisp/lang/runtime.py
- basilisp/lang/seq.py
- tests/atom_test.py
- tests/delay_test.py
- tests/runtime_test.py
- tests/seq_test.py
> Add atoms to core lib, supplement delay

- basilisp/compiler.py
- basilisp/lang/list.py
- basilisp/lang/runtime.py
- basilisp/lang/seq.py
- tests/runtime_test.py
- tests/seq_test.py
> Use an empty sequence object as a sentinel

- basilisp/compiler.py
- tests/compiler_test.py
> Allow anonymous functions to recursively call themselves

- basilisp/core/__init__.lpy
- basilisp/lang/associative.py
- basilisp/lang/map.py
- basilisp/lang/runtime.py
- basilisp/lang/seq.py
- basilisp/lang/set.py
- basilisp/lang/typing.py
- basilisp/lang/util.py
- basilisp/lang/vector.py
- tests/core_test.py
- tests/runtime_test.py
> Build out core library

- .gitignore
- Pipfile
- Pipfile.lock
- README.md
- basilisp/__version__.py
- setup.py
Prepare the repo for a `dev` release to PyPI.
> Prepare for a dev release to PyPI

- basilisp/reader.py
- tests/reader_test.py
> Add deref literal syntax to the reader

- basilisp/reader.py
- tests/reader_test.py
> Support for character literals

- basilisp/compiler.py
- tests/compiler_test.py
> Lazily evaluate let-binding expressions

- basilisp/compiler.py
- basilisp/core/__init__.lpy
- tests/compiler_test.py
> Support Clojure's object instantiation syntax

- basilisp/compiler.py
- tests/compiler_test.py
> Compiler support for dynamic vars

- basilisp/compiler.py
> Coerce catch/finally clause inputs to lists

- basilisp/reader.py
- tests/reader_test.py
> Allow callers to specify custom data readers

- basilisp/lang/map.py
> Add update-with method to Map

- basilisp/core/__init__.lpy
- basilisp/lang/map.py
- tests/core_test.py
- tests/map_test.py
> Map conj supports other maps

- basilisp/core/__init__.lpy
- basilisp/lang/runtime.py
> Read, eval, and binding

- basilisp/lang/map.py
- tests/map_test.py
> Fix map cons test

- Makefile
- Pipfile
- Pipfile.lock
- README.md
- basilisp/cli.py
- basilisp/main.py
- setup.py
> Add a basic CLI for Basilisp REPL

- basilisp/compiler.py
- basilisp/importer.py
- basilisp/lang/runtime.py
- basilisp/reader.py
- tests/compiler_test.py
- tests/reader_test.py
- tests/runtime_test.py
> Fix resolver bugs

- basilisp/cli.py
- basilisp/repl.lpy
> Add REPL utility vars

- basilisp/lang/keyword.py
- tests/keyword_test.py
> Keywords used in function position no longer produce error

- Makefile
> Disable DeprecationWarnings in test output

- basilisp/lang/seq.py
- tests/core_test.py
- tests/seq_test.py
> Realize lazy seqs when checking if they are empty

- basilisp/compiler.py
- tests/compiler_test.py
> Resolve macro symbols using all possible heuristics

- basilisp/cli.py
- basilisp/compiler.py
- basilisp/core/__init__.lpy
- basilisp/lang/runtime.py
- basilisp/repl.lpy
- tests/namespace_test.py
- tests/var_test.py
> Add namespace functions to basilisp.core

- basilisp/reader.py
- tests/reader_test.py
> Read escape sequences in string literals; read char literals inside other forms

- basilisp/string.lpy
- tests/string_test.py
> String library

- basilisp/core/__init__.lpy
- tests/core_test.py
> Add regex functions to core

- src/basilisp/compiler.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
> Return a useful error message if a Var isn't found

- src/basilisp/repl.lpy
> Fix REPL vars when switching namespaces

- src/basilisp/core/__init__.lpy
> Fix NS macro require emission

- tox.ini
> Use coverage instead of pytest-cov in tox

- src/basilisp/lang/runtime.py
- tests/basilisp/namespace_test.py
> Don't create non-existent namespaces in Var.find

- tests/basilisp/compiler_test.py
- tests/basilisp/namespace_test.py
- tests/basilisp/reader_test.py
- tests/basilisp/runtime_test.py
> Don't remove basilisp.core in tests

- src/basilisp/importer.py
- tests/basilisp/importer_test.py
> Do not add Importer again after it was initially added

- Pipfile
- Pipfile.lock
- setup.py
- src/basilisp/cli.py
- src/basilisp/test.lpy
- src/basilisp/testrunner.py
- tests/basilisp/conftest.py
- tests/basilisp/test_string.lpy
- tests/basilisp/testrunner_test.py
- tox.ini
> PyTest test runner for Basilisp

- src/basilisp/reader.py
- tests/basilisp/reader_test.py
> Handle reader comments in collections

- src/basilisp/cli.py
- src/basilisp/core/__init__.lpy
- src/basilisp/reader.py
- tests/basilisp/reader_test.py
> Custom EOF in Reader

- src/basilisp/core/__init__.lpy
- src/basilisp/lang/multifn.py
- tests/basilisp/multifn_test.py
> Add multi-methods to Basilisp

- src/basilisp/cli.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
- tests/basilisp/importer_test.py
- tests/basilisp/namespace_test.py
- tests/basilisp/reader_test.py
- tests/basilisp/runtime_test.py
> Use context managers to change *ns* in tests

- src/basilisp/reader.py
- tests/basilisp/reader_test.py
> Allow non-symbols in interop member position

- src/basilisp/test.lpy
- src/basilisp/testrunner.py
> Catch other exceptions in the test runner and print the traceback

- src/basilisp/compiler.py
- src/basilisp/core/__init__.lpy
- src/basilisp/lang/runtime.py
- tests/basilisp/test_multifn.lpy
> Fix import errors in multi-methods

- .prospector.yaml
- Makefile
- src/basilisp/cli.py
- src/basilisp/compiler.py
- src/basilisp/importer.py
- src/basilisp/lang/runtime.py
- src/basilisp/logging.py
- src/basilisp/main.py
> Add logging module to Basilisp

- src/basilisp/compiler.py
- src/basilisp/importer.py
- src/basilisp/util.py
> Implement bytecode caching in BasilispImporter

- src/basilisp/lang/keyword.py
- tests/basilisp/compiler_test.py
- tests/basilisp/core_test.py
- tests/basilisp/keyword_test.py
> Keyword str and repr are now the same

- src/basilisp/lang/compiler.py
> Fix spurious MyPy errors arising from 0.641 version of MyPy

- src/basilisp/importer.py
- tox.ini
> Add an option (as an environment var) to disable cached namespace imports

- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
> Reader will no longer resolve generated symbols in syntax-quote

- src/basilisp/test.lpy
- src/basilisp/testrunner.py
- tests/basilisp/testrunner_test.py
> Capture line numbers in Basilisp tests

- src/basilisp/core/__init__.lpy
- tests/basilisp/core_test.py
> Fix basilisp.core/map lazy seq behavior

- src/basilisp/lang/compiler.py
- tests/basilisp/compiler_test.py
> Allow empty function definitions

- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
> Allow dollar sign symbols

- src/basilisp/core/__init__.lpy
- src/basilisp/lang/compiler.py
- tests/basilisp/compiler_test.py
> Add meta flags to allow redefining Vars and to disable warnings on redef

- src/basilisp/core/__init__.lpy
- src/basilisp/lang/runtime.py
- tests/basilisp/core_test.py
> Prevent apply from swallowing exceptions

- src/basilisp/test.lpy
- src/basilisp/testrunner.py
- tests/basilisp/testrunner_test.py
> Report exceptions in testrunner as errors

- src/basilisp/cli.py
- src/basilisp/lang/compiler.py
- tests/basilisp/compiler_test.py
> Warn when emitting code which uses Var indirection

- src/basilisp/core/__init__.lpy
- src/basilisp/lang/compiler.py
- src/basilisp/logconfig.py
- src/basilisp/main.py
- tests/basilisp/compiler_test.py
> Emit a compiler warning when a local symbol is unused

- src/basilisp/core/__init__.lpy
- src/basilisp/lang/compiler.py
- src/basilisp/lang/exception.py
- src/basilisp/lang/keyword.py
- src/basilisp/lang/list.py
- src/basilisp/lang/map.py
- src/basilisp/lang/meta.py
- src/basilisp/lang/obj.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/seq.py
- src/basilisp/lang/set.py
- src/basilisp/lang/symbol.py
- src/basilisp/lang/util.py
- src/basilisp/lang/vector.py
- src/basilisp/testrunner.py
- src/basilisp/util.py
- tests/basilisp/lrepr_test.py
> Produce a Lisp string representation from LispObject ABC

- src/basilisp/cli.py
- src/basilisp/core/__init__.lpy
- src/basilisp/importer.py
- src/basilisp/lang/compiler.py
- tests/basilisp/compiler_test.py
> Attach meta to def forms in compiler

- src/basilisp/lang/compiler.py
- tests/basilisp/compiler_test.py
> Do not evaluate quoted interop forms

- src/basilisp/lang/compiler/__init__.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/compiler/parser.py
- src/basilisp/lang/keyword.py
- src/basilisp/lang/map.py
- src/basilisp/lang/obj.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/symbol.py
- src/basilisp/lang/typing.py
- tests/basilisp/compiler_test.py
- tests/basilisp/lrepr_test.py
- tests/basilisp/reader_test.py
> Create Python literals using #py reader tag

- src/basilisp/core/__init__.lpy
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/compiler/parser.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
- tests/basilisp/runtime_test.py
> Pass macro environment as the first argument to macro functions

- src/basilisp/cli.py
- src/basilisp/lang/keyword.py
- src/basilisp/lang/runtime.py
- tests/basilisp/keyword_test.py
- tests/basilisp/namespace_test.py
> Symbol and keyword readline completers

- Makefile
- src/basilisp/cli.py
- tests/basilisp/cli_test.py
> Support reading Basilisp code from CLI stdin

- src/basilisp/core/__init__.lpy
- src/basilisp/lang/compiler/constants.py
- src/basilisp/lang/compiler/parser.py
- tests/basilisp/core_macros_test.lpy
> Attach metadata via defn attribute map

- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/compiler/parser.py
- tests/basilisp/compiler_test.py
> Nested module imports are no longer obscured by their parent module

- CHANGELOG.md
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/runtime.py
> Use Python module aliases for Basilisp lang references

- src/basilisp/core/__init__.lpy
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/seq.py
- tests/basilisp/core_macros_test.lpy
- tests/basilisp/core_test.py
- tests/basilisp/list_test.py
- tests/basilisp/map_test.py
> More core library functions and macros

- src/basilisp/lang/compiler/__init__.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/exception.py
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
> Rename parser to analyzer to reflect its true purpose

- src/basilisp/core/__init__.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/nodes.py
- tests/basilisp/compiler_test.py
> Allow referring to static methods directly

- tests/basilisp/core_macros_test.lpy
- tests/basilisp/core_test.py
I am bad and didn't write this in #401 so I'm adding them here.
> String formatting function tests

- Pipfile
- src/basilisp/core.lpy
- src/basilisp/importer.py
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/list.py
- src/basilisp/lang/map.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/vector.py
- tests/basilisp/compiler_test.py
- tests/basilisp/core_macros_test.lpy
- tests/basilisp/namespace_test.py
- tests/basilisp/runtime_test.py
- tests/basilisp/var_test.py
Add some new `Namespace` and `Var` functions to `basilisp.core` and supplement a few existing ones.
> Add several new namespace functions

- Pipfile.lock
- src/basilisp/_pyast.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/seq.py
- tests/basilisp/core_test.py
- tests/basilisp/seq_test.py
> Ensure seq type iterators don't reach recursion limit

- .circleci/config.yml
- tests/basilisp/importer_test.py
> Fix Importer tests so they work on all platforms

- .circleci/config.yml
- Pipfile.lock
- setup.py
- src/basilisp/importer.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/exception.py
- src/basilisp/lang/map.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/runtime.py
- src/basilisp/testrunner.py
- tox.ini
Support the full Python 3.8 release.
> Support Python 3.8 release

- .circleci/config.yml
- .prospector.yaml
- Makefile
- src/basilisp/lang/compiler/generator.py
- tox.ini
> Compile attrs instances without cmp kwarg if version >= 19.2.0

- src/basilisp/core.lpy
- src/basilisp/lang/atom.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/list.py
- src/basilisp/lang/map.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/reference.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/seq.py
- src/basilisp/lang/set.py
- src/basilisp/lang/symbol.py
- src/basilisp/lang/util.py
- src/basilisp/lang/vector.py
- tests/basilisp/atom_test.py
- tests/basilisp/core_fns_test.lpy
- tests/basilisp/list_test.py
- tests/basilisp/map_test.py
- tests/basilisp/namespace_test.py
- tests/basilisp/set_test.py
- tests/basilisp/symbol_test.py
- tests/basilisp/var_test.py
- tests/basilisp/vector_test.py
- tox.ini
> Meta utility functions

- src/basilisp/core.lpy
> Primitive type coercion

- src/basilisp/core.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/interfaces.py
- src/basilisp/test.lpy
- tests/basilisp/compiler_test.py
> Fix line and column metadata

- src/basilisp/lang/compiler/analyzer.py
> Improve nested symbol exception message

- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
> Warnings for Lisp code point to Lisp code

- .prospector.yaml
- CHANGELOG.md
- Pipfile.lock
- docs/gettingstarted.rst
- docs/reader.rst
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/runtime.py
- tests/basilisp/cli_test.py
- tox.ini
> Change the default user namespace to `basilisp.user`

- CHANGELOG.md
- docs/conf.py
- docs/reader.rst
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
> Support Shebang style line comments

- CHANGELOG.md
- src/basilisp/lang/multifn.py
> Use a `threading.Lock` internally for multi-methods

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/constants.py
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
>  Fully namespace-qualified symbols should resolve regardless of current Namespace aliases

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/cli_test.py
> Improved reader syntax errors

- src/basilisp/lang/compiler/exception.py
- tests/basilisp/cli_test.py
> Add useful context information to the CompilerException class

- src/basilisp/importer.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/runtime.py
- tests/basilisp/reader_test.py
- tests/basilisp/runtime_test.py
> Accept namespaces or symbols in Var.intern and Var.find APIs

- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
- tests/basilisp/helpers.py
> Remove unused Analyzer branches for resolving Vars

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/obj.py
- tests/basilisp/core_fns_test.lpy
- tests/basilisp/core_macros_test.lpy
- tests/basilisp/prompt_test.py
> Arrays (Python lists)

- CHANGELOG.md
- src/basilisp/cli.py
- src/basilisp/importer.py
- src/basilisp/lang/compiler/__init__.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/typing.py
- src/basilisp/main.py
- src/basilisp/testrunner.py
- tests/basilisp/compiler_test.py
- tests/basilisp/core_test.py
- tests/basilisp/importer_test.py
- tests/basilisp/string_test.py
> Intern *compiler-options* so it can be reused on require

- CHANGELOG.md
- src/basilisp/core.lpy
> Dummy array casts

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- tests/basilisp/compiler_test.py
> Fixed a bug where private Vars could be referenced from a Namespace via alias

- CHANGELOG.md
- src/basilisp/shell.lpy
> Add `basilisp.shell` namespace

- CHANGELOG.md
- src/basilisp/core/template.lpy
> Add `apply-template` function to `basilisp.core.template`

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
> Fixed a collection reader bug with trailing end tokens separated by comments

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- tests/basilisp/compiler_test.py
> Correctly set node syntax position for deftype members

- CHANGELOG.md
- Pipfile.lock
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
- tests/basilisp/core_test.py
> Add support for calling Python functions and methods with keyword arguments

- CHANGELOG.md
- docs/reference.rst
- docs/typesandrecords.rst
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
> Multi-arity methods for deftype forms

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
> Intern Deftypes as Vars and resolve static and class methods

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/keyword.py
- src/basilisp/lang/map.py
- tests/basilisp/conftest.py
- tests/basilisp/keyword_test.py
- tests/basilisp/list_test.py
- tests/basilisp/map_test.py
- tests/basilisp/set_test.py
- tests/basilisp/symbol_test.py
- tests/basilisp/vector_test.py
> Allow builtin Basilisp types to be pickled

- CHANGELOG.md
- src/basilisp/lang/list.py
- src/basilisp/lang/map.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/seq.py
- src/basilisp/lang/set.py
- src/basilisp/lang/vector.py
- tests/basilisp/list_test.py
- tests/basilisp/map_test.py
- tests/basilisp/seq_test.py
- tests/basilisp/set_test.py
- tests/basilisp/vector_test.py
> Builtin collection types should always evaluate as True

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/set.lpy
- tests/basilisp/test_core_fns.lpy
> Fix the definition of `reduce`

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
> Add support for auto-resolved namespaces for keywords

- CHANGELOG.md
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
> Add support for namespaced map syntax

- CHANGELOG.md
- src/basilisp/lang/obj.py
- src/basilisp/lang/reader.py
- tests/basilisp/lrepr_test.py
- tests/basilisp/reader_test.py
> Add support for NaN, positive infinity, and negative infinity literals

- CHANGELOG.md
- src/basilisp/lang/runtime.py
> Add Basilisp and Python version vars to `basilisp.core`

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/reader.py
> Add support for decorators in `defn` and support conditional Python version compilation

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/runtime.py
- src/basilisp/lang/seq.py
- tests/basilisp/test_core_macros.lpy
> Fix RecursionError with concat and LazySeqs 

- CHANGELOG.md
- Pipfile
- Pipfile.lock
- mypy.ini
- setup.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/obj.py
- src/basilisp/lang/reader.py
- src/basilisp/util.py
- tests/basilisp/maybe_test.py
> Remove PyFunctional dependency

- .circleci/config.yml
- CHANGELOG.md
- src/basilisp/lang/reader.py
- src/basilisp/lang/runtime.py
- tests/basilisp/runtime_test.py
Fixes #358 (even more than before 😂 )
> Added default reader features for matching Python version ranges

- .circleci/config.yml
- Pipfile
- Pipfile.lock
- setup.py
- src/basilisp/lang/compiler/__init__.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/optimizer.py
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/keyword.py
- src/basilisp/lang/map.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/set.py
- src/basilisp/prompt.py
- src/basilisp/testrunner.py
- tests/basilisp/compiler_test.py
- tests/basilisp/core_test.py
- tests/basilisp/lrepr_test.py
- tests/basilisp/namespace_test.py
- tests/basilisp/prompt_test.py
- tests/basilisp/reader_test.py
- tests/basilisp/runtime_test.py
- tox.ini
> Support Python 3.9

- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
> A few more seq utility functions

- CHANGELOG.md
- src/basilisp/main.py
> Improve the Basilisp bootstrapping experience

- CHANGELOG.md
- pyproject.toml
- src/basilisp/cli.py
- src/basilisp/testrunner.py
- tests/basilisp/cli_test.py
- tox.ini
> Remove Click and make PyTest an extra dependency

- .circleci/config.yml
- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/atom.py
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/reference.py
- src/basilisp/lang/runtime.py
- tests/basilisp/atom_test.py
- tests/basilisp/var_test.py
- tox.ini
> Add ref watches and validators

- tests/basilisp/test_defrecord.lpy
> Test various record and type constructor styles

- src/basilisp/core.lpy
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/list.py
- src/basilisp/lang/map.py
- src/basilisp/lang/queue.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/seq.py
- src/basilisp/lang/set.py
- src/basilisp/lang/vector.py
- tests/basilisp/list_test.py
- tests/basilisp/map_test.py
- tests/basilisp/queue_test.py
- tests/basilisp/set_test.py
- tests/basilisp/test_core_fns.lpy
- tests/basilisp/vector_test.py
> Fix stack overflow resulting from co-recursive lazy seqs

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/test.lpy
- tests/basilisp/test_core_fns.lpy
> Add support for taps

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
- tests/basilisp/test_core_macros.lpy
> Allow multiple expressions to appear in a try form body

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/reference.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
- tests/basilisp/namespace_test.py
- tests/basilisp/var_test.py
> Update metadata and dynamic flag on Var redef

- src/basilisp/core.lpy
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/multifn.py
- src/basilisp/lang/reference.py
- tests/basilisp/test_multifn.lpy
> Support isa? based dispatch in multimethods

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/io.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/multifn.py
- src/basilisp/lang/obj.py
- src/basilisp/testrunner.py
- tests/basilisp/test_io.lpy
> basilisp.io namespace

- CHANGELOG.md
- Makefile
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/analyzer.py
> Disallow private Vars to be resolved within macros during macroexpansion

- .circleci/config.yml
- CHANGELOG.md
- src/basilisp/edn.lpy
- src/basilisp/lang/reader.py
- tests/basilisp/compiler_test.py
- tests/basilisp/reader_test.py
- tests/basilisp/test_edn.lpy
> Allow trailing single quotes in Symbols and Keywords

- CHANGELOG.md
- src/basilisp/io.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/constants.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
> Support `yield` statement for creating coroutines

- CHANGELOG.md
- docs/differencesfromclojure.rst
> Add differences from Clojure documentation

- CHANGELOG.md
- docs/differencesfromclojure.rst
- src/basilisp/core.lpy
> Rewrite 'clojure.' requires into 'basilisp.'

- CHANGELOG.md
- docs/differencesfromclojure.rst
- src/basilisp/core.lpy
> Fix auto namespace rewriting to be auto-aliasing

- .gitignore
- CHANGELOG.md
- pyproject.toml
- src/basilisp/contrib/sphinx/autodoc.py
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/obj.py
- tests/basilisp/core_test.py
- tests/basilisp/lrepr_test.py
- tests/basilisp/test_core_fns.lpy
- tox.ini
> Add support for Clojure 1.11 core functions

- .circleci/config.yml
- .github/workflows/run-tests.yml
- CHANGELOG.md
- pyproject.toml
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/exception.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/runtime.py
- tests/basilisp/compiler_test.py
- tests/basilisp/reader_test.py
- tests/basilisp/runtime_test.py
- tests/basilisp/testrunner_test.py
- tox.ini
> Add support for Python 3.11

- .github/workflows/pypi-release.yml
- .github/workflows/run-tests.yml
- Makefile
Github Action workflow to release new versions of Basilisp to PyPI after cutting releases on Github.
> Github Action to release to PyPI

- CHANGELOG.md
- docs/reader.rst
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/obj.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/typing.py
- tests/basilisp/lrepr_test.py
- tests/basilisp/reader_test.py
> Add support for bytes literals

- .github/workflows/run-tests.yml
- CHANGELOG.md
- docs/pyinterop.rst
- pyproject.toml
- src/basilisp/lang/map.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/set.py
- tests/basilisp/compiler_test.py
- tests/basilisp/runtime_test.py
- tests/basilisp/testrunner_test.py
- tox.ini
> Support Python 3.12

- CHANGELOG.md
- src/basilisp/__version__.py
- src/basilisp/cli.py
- src/basilisp/lang/runtime.py
> Use importlib.metadata to surface Basilisp version

- CHANGELOG.md
- docs/reader.rst
- src/basilisp/io.lpy
- src/basilisp/lang/runtime.py
- tests/basilisp/runtime_test.py
> Add a default reader conditional for the current platform

- CHANGELOG.md
- docs/api/contrib/bencode.rst
- src/basilisp/contrib/bencode.lpy
- src/basilisp/lang/runtime.py
- tests/basilisp/contrib/bencode_test.lpy
> Support bencode for nrepl server

- CHANGELOG.md
- src/basilisp/core.lpy
> Remove :inline designation for certain core functions

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/runtime.py
- tests/basilisp/runtime_test.py
Hi,
could you please review fix for `(count nil)` to return 0. Fixes #759.
Rudimentary tests added for `count`. Thanks
> baislisp.core/count should return 0 on nil input

- CHANGELOG.md
- docs/gettingstarted.rst
- pyproject.toml
- src/basilisp/cli.py
- tests/basilisp/cli_test.py
- tests/basilisp/conftest.py
> Support shebangs with a single argument

- CHANGELOG.md
- src/basilisp/lang/runtime.py
> Autocomplete `python/` namespace at the REPL

- CHANGELOG.md
- Makefile
- docs/cli.rst
- docs/contributing.rst
- docs/gettingstarted.rst
- src/basilisp/cli.py
- src/basilisp/importer.py
- src/basilisp/lang/runtime.py
- src/basilisp/main.py
- src/basilisp/sitecustomize.py
- tests/basilisp/cli_test.py
- tests/basilisp/importer_test.py
- tox.ini
> Add a CLI subcommand for bootstrapping the Python installation

- CHANGELOG.md
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
> Improve `if` and `let*` form Python generation

- CHANGELOG.md
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
> Improve Python generation for `do` and `letfn*` forms

- CHANGELOG.md
- pyproject.toml
- src/basilisp/cli.py
- src/basilisp/importer.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/exception.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- src/basilisp/lang/delay.py
- src/basilisp/lang/exception.py
- src/basilisp/lang/futures.py
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/obj.py
- src/basilisp/lang/promise.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/reduced.py
- src/basilisp/lang/runtime.py
- src/basilisp/lang/seq.py
- src/basilisp/lang/symbol.py
- src/basilisp/lang/vector.py
- src/basilisp/lang/volatile.py
- src/basilisp/util.py
- tests/basilisp/reader_test.py
Second attempt to pare down the failing PyPy build for #784
> Improve the state of Python type hints in `basilisp.lang.*`

- CHANGELOG.md
- pyproject.toml
> Loosen data structure library dependency specifications

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/prompt_test.py
- tests/basilisp/test_core_fns.lpy
Hi,
could you please consider an implementation of the `memoize` core fn. It fixes #812.
Also added some basic tests.
Thanks
> Added the `memoize` core fn

- CHANGELOG.md
- docs/requirements.txt
- pyproject.toml
- src/basilisp/contrib/sphinx/autodoc.py
Fixes #815 in a more complete way (hopefully)
> Update Sphinx to ^7.1.0

- .github/workflows/run-tests.yml
- CHANGELOG.md
- docs/reader.rst
- src/basilisp/contrib/sphinx/autodoc.py
- src/basilisp/edn.lpy
- src/basilisp/lang/reader.py
- tests/basilisp/reader_test.py
> Support a wider array of integer literals

- CHANGELOG.md
- docs/concepts.rst
- docs/pyinterop.rst
- docs/reader.rst
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
> Support trailing maps in keyword argument destructuring

- CHANGELOG.md
- docs/concepts.rst
- src/basilisp/core.lpy
- tests/basilisp/namespace_test.py
> Support requiring namespaces as aliases only

- pyproject.toml
- src/basilisp/cli.py
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/seq.py
- tox.ini
Black v2024.1 introduced some formatting changes that are somewhat noisy in portions of the compiler. This is just a separate PR to run it separate of other functional changes.
> Format with Black v2024.1

- CHANGELOG.md
- src/basilisp/contrib/nrepl_server.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/exception.py
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/contrib/nrepl_server_test.lpy
> Improve Compiler Exception metadata handling

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/reader.py
> Stop chaining macroexpansion exceptions during compilation

- CHANGELOG.md
- src/basilisp/lang/reader.py
> Add line and column information to exceptions from reading reader conditionals

- CHANGELOG.md
- docs/specialforms.rst
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
- tests/basilisp/compiler_test.py
> Add support for explicit exception cause chaining to the throw special form

- src/basilisp/lang/interfaces.py
- src/basilisp/lang/keyword.py
- src/basilisp/lang/symbol.py
> Support creating new INamed instances via classmethod

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- tests/basilisp/compiler_test.py
> Don't throw an exception on macroexpanding recur

- CHANGELOG.md
- src/basilisp/lang/obj.py
- tests/basilisp/lrepr_test.py
> Properly escape string output at the REPL

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/runtime.py
- tests/basilisp/test_core_fns.lpy
> Allow creating keywords and symbols from other keywords and symbols

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/compiler_test.py
> Fix an erroneous compiler warning on Var redef

- CHANGELOG.md
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/reader.py
- src/basilisp/lang/source.py
- tests/basilisp/cli_test.py
- tests/basilisp/compiler_test.py
- tests/basilisp/reader_test.py
> Fix reader column offset numbering

- docs/api/repl.rst
- docs/gettingstarted.rst
- docs/repl.rst
- src/basilisp/io.lpy
- src/basilisp/json.lpy
- src/basilisp/main.py
- src/basilisp/prompt.py
- src/basilisp/repl.lpy
- src/basilisp/string.lpy
> Add REPL documentation module

- CHANGELOG.md
- Makefile
- docs/interfaces.rst
- docs/reference.rst
- src/basilisp/core.lpy
- src/basilisp/lang/interfaces.py
- src/basilisp/lang/obj.py
- src/basilisp/lang/reference.py
- src/basilisp/lang/runtime.py
- tests/basilisp/core_test.py
- tests/basilisp/test_core_fns.lpy
Add some initial documentation around the Python interfaces which underpin most Basilisp collection functions.
> Add documentation for Basilisp interfaces

- CHANGELOG.md
- docs/conf.py
- src/basilisp/contrib/sphinx/__init__.py
- src/basilisp/contrib/sphinx/autodoc.py
- src/basilisp/contrib/sphinx/domain.py
- src/basilisp/contrib/sphinx/linkcode.py
> Add Github source links to generated API documentation

- CHANGELOG.md
- docs/concepts.rst
- docs/index.rst
- docs/reader.rst
- docs/reference.rst
- docs/repl.rst
- docs/runtime.rst
- src/basilisp/core.lpy
> Additional documentation fixes and updates

- CHANGELOG.md
- docs/concepts.rst
- docs/runtime.rst
Continuing to whittle away at #666
> More concepts documentation

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/vector.py
- tests/basilisp/vector_test.py
> Make vectors callable to get values by index

- CHANGELOG.md
- src/basilisp/lang/seq.py
> Make LazySeq evaluation thread-safe

- docs/concepts.rst
- docs/differencesfromclojure.rst
- docs/pyinterop.rst
- docs/reader.rst
- docs/specialforms.rst
- src/basilisp/lang/interfaces.py
> Concepts documentation module

- CHANGELOG.md
- src/basilisp/cli.py
- src/basilisp/contrib/nrepl_server.lpy
- src/basilisp/importer.py
- src/basilisp/lang/compiler/__init__.py
> Fix some uses of eval'ed code using string interpolation

- docs/concepts.rst
> More concepts module documentation

- CHANGELOG.md
- src/basilisp/lang/reader.py
> Don't suppress reading record and custom data reader types

- docs/concepts.rst
- src/basilisp/core.lpy
> Final concepts documentation module

- CHANGELOG.md
- docs/concepts.rst
- src/basilisp/core.lpy
- src/basilisp/lang/keyword.py
- tests/basilisp/contrib/nrepl_server_test.lpy
- tests/basilisp/core_test.py
- tests/basilisp/keyword_test.py
- tests/basilisp/test_core_fns.lpy
> Adds in some missing functions to `basilisp.core`

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_core_fns.lpy
> Fix  keep and keep-indexed two-arity forms (#962)

- CHANGELOG.md
- docs/differencesfromclojure.rst
- src/basilisp/lang/compiler/generator.py
- src/basilisp/pprint.lpy
- tests/basilisp/test_pprint.lpy
> `basilisp.pprint/print-table` function

- CHANGELOG.md
- src/basilisp/cli.py
> Add missing compiler arguments to cli commands

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/optimizer.py
- src/basilisp/lang/util.py
- tests/basilisp/core_test.py
- tests/basilisp/keyword_test.py
- tests/basilisp/symbol_test.py
> Fix Python SyntaxWarnings generated by compiled code

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/core_test.py
- tests/basilisp/test_core_fns.lpy
> Fix higher arities of the range function

- CHANGELOG.md
- docs/concepts.rst
- src/basilisp/core.lpy
- tests/basilisp/test_core_macros.lpy
> Support destructuring namespaced symbols

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/runtime.py
- src/basilisp/lang/vector.py
- tests/basilisp/keyword_test.py
- tests/basilisp/test_core_fns.lpy
> Fix nil behaviour with collection types #1011

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/runtime.py
- src/basilisp/lang/vector.py
- tests/basilisp/core_test.py
- tests/basilisp/test_core_fns.lpy
> Support more data types in keys and vals

- CHANGELOG.md
- src/basilisp/lang/seq.py
- tests/basilisp/seq_test.py
> Fix lazy sequences not propagating AttributeError #1019

- CHANGELOG.md
- src/basilisp/lang/compiler/analyzer.py
> Allow disabling function inlining

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_defrecord.lpy
> Fix deftype/defrecord constructors #1025

- CHANGELOG.md
- src/basilisp/core.lpy
- tests/basilisp/test_defrecord.lpy
> Fix record iterator and __getitem__ methods #1030

- .github/workflows/run-tests.yml
- CHANGELOG.md
- pyproject.toml
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/generator.py
- tests/basilisp/test_defrecord.lpy
> Fix a bug with using fields with special characters in records

- CHANGELOG.md
- src/basilisp/core.lpy
- src/basilisp/lang/compiler/analyzer.py
- src/basilisp/lang/compiler/constants.py
- src/basilisp/lang/compiler/generator.py
- src/basilisp/lang/compiler/nodes.py
> Don't force all top-level `do` forms to use Var indirection

- .github/workflows/run-tests.yml
- CHANGELOG.md
- README.md
- docs/gettingstarted.rst
- pyproject.toml
Fixes #1089 (by simply reverting it)
> Prepare for Release v0.3.0

- .github/workflows/run-tests.yml
- CHANGELOG.md
- src/basilisp/core.lpy
> Fix a bug where multi-arity `defn`s could not be emitted by macros

- CHANGELOG.md
- src/basilisp/core.lpy
> Fix `ns` macro metadata regression
